import {
  Image as ImageIcon,
  Code2,
  Megaphone,
  PenTool,
  Music,
  Zap,
  Palette,
  GraduationCap,
  Box,
  Search,
  MessageSquare,
  Briefcase,
  Bot,
  Video,
  Database,
  LayoutTemplate,
  Shield,
  HeartPulse,
  Scale,
  ShoppingCart,
  Gamepad2,
  Mic2,
  Film,
  Sparkles,
  LineChart,
  Workflow,
  Cpu,
  Globe2,
  Users,
  BookOpen,
  Camera,
  Headphones,
  Building2,
  Stethoscope,
  Landmark,
  Languages,
  Binary,
  Rocket,
  Layers,
  Wrench,
  Brain,
  Car,
  Plane,
  Leaf,
  Baby,
  Shirt,
  Utensils,
  Dumbbell,
  Clapperboard,
  Newspaper,
  Mail,
  Calendar,
  FileText,
  PieChart,
  BarChart3,
  Network,
  Cloud,
  Lock,
  Eye,
  Scissors,
  Paintbrush,
  Type,
  AudioLines,
  Radio,
  Podcast,
  Store,
  Truck,
  Factory,
  FlaskConical,
  Atom,
  Telescope,
  School,
  University,
  Handshake,
  Target,
  TrendingUp,
  Wallet,
  Receipt,
  Gavel,
  Fingerprint,
  Bug,
  Server,
  Terminal,
  Braces,
  GitBranch,
  AppWindow,
  Smartphone,
  Watch,
  Home,
  Trees,
  Mountain,
  Ship,
  Bike,
  Church,
  PawPrint,
  Flower2,
  Coffee,
  Wine,
  Hotel,
  MapPin,
  Compass,
  Lightbulb,
  Puzzle,
  Timer,
  ListTodo,
  StickyNote,
  Presentation,
  Table,
  FormInput,
  QrCode,
  Share2,
  Hash,
  AtSign,
  MessagesSquare,
  PhoneCall,
  Headset,
  UserCog,
  IdCard,
  BadgeCheck,
  Package,
  Boxes,
  Warehouse,
  Recycle,
  Wind,
  Sun,
  Droplets,
  Flame,
  Snowflake,
  Accessibility,
  HandHeart,
  Smile,
  Drama,
  Music2,
  Piano,
  Guitar,
  Disc3,
  ImagePlus,
  Images,
  Aperture,
  Focus,
  Crop,
  Wand2,
  Blend,
  Shapes,
  Cuboid,
  Orbit,
  CircuitBoard,
  Microchip,
  BotMessageSquare,
  Speech,
  Captions,
  Subtitles,
  ScanText,
  FileSearch,
  FolderSearch,
  Library,
  ScrollText,
  NotebookPen,
  PenLine,
  Quote,
  SpellCheck,
  WholeWord,
  Sigma,
  Calculator,
  ChartSpline,
  Activity,
  Crosshair,
  Swords,
  Trophy,
  Dices,
  Joystick,
  Popcorn,
  Tv,
  MonitorPlay,
  Webcam,
  Printer,
  HardDrive,
  Usb,
  Wifi,
  Bluetooth,
  BatteryCharging,
  Plug,
  Cable,
} from 'lucide-react';
import { normalizeCategoryLookupKey } from '@/lib/categoryLookup';
import { PRIMARY_CATEGORIES, isPrimaryCategorySlug, CATEGORY_GROUPS } from '@/lib/categoryTaxonomy';

const ICONS = {
  ImageIcon,
  Code2,
  Megaphone,
  PenTool,
  Music,
  Zap,
  Palette,
  GraduationCap,
  Box,
  Search,
  MessageSquare,
  Briefcase,
  Bot,
  Video,
  Database,
  LayoutTemplate,
  Shield,
  HeartPulse,
  Scale,
  ShoppingCart,
  Gamepad2,
  Mic2,
  Film,
  Sparkles,
  LineChart,
  Workflow,
  Cpu,
  Globe2,
  Users,
  BookOpen,
  Camera,
  Headphones,
  Building2,
  Stethoscope,
  Landmark,
  Languages,
  Binary,
  Rocket,
  Layers,
  Wrench,
  Brain,
  Car,
  Plane,
  Leaf,
  Baby,
  Shirt,
  Utensils,
  Dumbbell,
  Clapperboard,
  Newspaper,
  Mail,
  Calendar,
  FileText,
  PieChart,
  BarChart3,
  Network,
  Cloud,
  Lock,
  Eye,
  Scissors,
  Paintbrush,
  Type,
  AudioLines,
  Radio,
  Podcast,
  Store,
  Truck,
  Factory,
  FlaskConical,
  Atom,
  Telescope,
  School,
  University,
  Handshake,
  Target,
  TrendingUp,
  Wallet,
  Receipt,
  Gavel,
  Fingerprint,
  Bug,
  Server,
  Terminal,
  Braces,
  GitBranch,
  AppWindow,
  Smartphone,
  Watch,
  Home,
  Trees,
  Mountain,
  Ship,
  Bike,
  Church,
  PawPrint,
  Flower2,
  Coffee,
  Wine,
  Hotel,
  MapPin,
  Compass,
  Lightbulb,
  Puzzle,
  Timer,
  ListTodo,
  StickyNote,
  Presentation,
  Table,
  FormInput,
  QrCode,
  Share2,
  Hash,
  AtSign,
  MessagesSquare,
  PhoneCall,
  Headset,
  UserCog,
  IdCard,
  BadgeCheck,
  Package,
  Boxes,
  Warehouse,
  Recycle,
  Wind,
  Sun,
  Droplets,
  Flame,
  Snowflake,
  Accessibility,
  HandHeart,
  Smile,
  Drama,
  Music2,
  Piano,
  Guitar,
  Disc3,
  ImagePlus,
  Images,
  Aperture,
  Focus,
  Crop,
  Wand2,
  Blend,
  Shapes,
  Cuboid,
  Orbit,
  CircuitBoard,
  Microchip,
  BotMessageSquare,
  Speech,
  Captions,
  Subtitles,
  ScanText,
  FileSearch,
  FolderSearch,
  Library,
  ScrollText,
  NotebookPen,
  PenLine,
  Quote,
  SpellCheck,
  WholeWord,
  Sigma,
  Calculator,
  ChartSpline,
  Activity,
  Crosshair,
  Swords,
  Trophy,
  Dices,
  Joystick,
  Popcorn,
  Tv,
  MonitorPlay,
  Webcam,
  Printer,
  HardDrive,
  Usb,
  Wifi,
  Bluetooth,
  BatteryCharging,
  Plug,
  Cable,
  LayoutTemplate,
};

const COLORS = {
  purple: {
    color: 'purple',
    gradient: 'from-purple-500/20 to-fuchsia-500/20',
    border: 'border-purple-500/30',
    text: 'text-purple-500',
  },
  blue: {
    color: 'blue',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
  },
  orange: {
    color: 'orange',
    gradient: 'from-orange-500/20 to-amber-500/20',
    border: 'border-orange-500/30',
    text: 'text-orange-500',
  },
  green: {
    color: 'green',
    gradient: 'from-green-500/20 to-emerald-500/20',
    border: 'border-green-500/30',
    text: 'text-green-500',
  },
  rose: {
    color: 'rose',
    gradient: 'from-rose-500/20 to-pink-500/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
  },
  yellow: {
    color: 'yellow',
    gradient: 'from-yellow-500/20 to-amber-400/20',
    border: 'border-yellow-500/30',
    text: 'text-yellow-500',
  },
  pink: {
    color: 'pink',
    gradient: 'from-pink-500/20 to-rose-400/20',
    border: 'border-pink-500/30',
    text: 'text-pink-500',
  },
  indigo: {
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-blue-500/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
  },
  teal: {
    color: 'teal',
    gradient: 'from-teal-500/20 to-emerald-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
  },
  cyan: {
    color: 'cyan',
    gradient: 'from-cyan-500/20 to-blue-400/20',
    border: 'border-cyan-500/30',
    text: 'text-cyan-500',
  },
  violet: {
    color: 'violet',
    gradient: 'from-violet-500/20 to-purple-500/20',
    border: 'border-violet-500/30',
    text: 'text-violet-500',
  },
  slate: {
    color: 'slate',
    gradient: 'from-slate-500/20 to-gray-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
  },
  fuchsia: {
    color: 'fuchsia',
    gradient: 'from-fuchsia-500/20 to-purple-400/20',
    border: 'border-fuchsia-500/30',
    text: 'text-fuchsia-500',
  },
  red: {
    color: 'red',
    gradient: 'from-red-500/20 to-orange-400/20',
    border: 'border-red-500/30',
    text: 'text-red-500',
  },
  amber: {
    color: 'amber',
    gradient: 'from-amber-500/20 to-yellow-400/20',
    border: 'border-amber-500/30',
    text: 'text-amber-500',
  },
  sky: {
    color: 'sky',
    gradient: 'from-sky-500/20 to-blue-400/20',
    border: 'border-sky-500/30',
    text: 'text-sky-500',
  },
  emerald: {
    color: 'emerald',
    gradient: 'from-emerald-500/20 to-teal-400/20',
    border: 'border-emerald-500/30',
    text: 'text-emerald-500',
  },
  stone: {
    color: 'stone',
    gradient: 'from-stone-500/20 to-amber-400/20',
    border: 'border-stone-500/30',
    text: 'text-stone-500',
  },
  lime: {
    color: 'lime',
    gradient: 'from-lime-500/20 to-green-400/20',
    border: 'border-lime-500/30',
    text: 'text-lime-500',
  },
};

/**
 * Tek kaynak: PRIMARY_CATEGORIES (daraltılmış ~25 ana kategori)
 */
const CATEGORY_DEFS = PRIMARY_CATEGORIES.map((c) => [
  c.name,
  c.slug,
  c.iconKey,
  c.colorKey,
  c.description,
]);

function buildFromDefs(defs) {
  const config = {};
  const seed = [];

  for (const [name, slug, iconKey, colorKey, description] of defs) {
    const colorTheme = COLORS[colorKey] || COLORS.slate;
    const icon = ICONS[iconKey] || LayoutTemplate;
    config[slug] = {
      icon,
      ...colorTheme,
      description,
    };
    seed.push({ name, slug });
  }

  return { config, seed };
}

const built = buildFromDefs(CATEGORY_DEFS);

export const categoryConfig = built.config;
export const CATEGORY_SEED = built.seed;
export const CATEGORY_ORDER = new Map(
  CATEGORY_SEED.map((category, index) => [category.slug, index])
);

export const defaultCategoryConfig = {
  icon: LayoutTemplate,
  color: 'primary',
  gradient: 'from-primary/20 to-primary/10',
  border: 'border-primary/30',
  text: 'text-primary',
  description: 'Bu kategori altındaki en yenilikçi ve popüler yapay zeka araçlarını keşfedin.',
};

export function getCategoryConfig(slug) {
  return categoryConfig[slug] || defaultCategoryConfig;
}

export function getCategoryCount() {
  return CATEGORY_SEED.length;
}

export { isPrimaryCategorySlug, CATEGORY_GROUPS, PRIMARY_CATEGORIES };

/** Sadece kanonik (primary) kategorileri tut; merge sonrası UI için. */
export function filterPrimaryCategories(categories = []) {
  return categories.filter((c) => isPrimaryCategorySlug(c.slug));
}

function normalizeCategoryValue(value) {
  return normalizeCategoryLookupKey(value);
}

export function sortCategoriesByCanonicalOrder(categories = []) {
  return [...categories].sort((a, b) => {
    const aOrder = CATEGORY_ORDER.has(a.slug)
      ? CATEGORY_ORDER.get(a.slug)
      : Number.MAX_SAFE_INTEGER;
    const bOrder = CATEGORY_ORDER.has(b.slug)
      ? CATEGORY_ORDER.get(b.slug)
      : Number.MAX_SAFE_INTEGER;

    if (aOrder !== bOrder) return aOrder - bOrder;

    return normalizeCategoryValue(a.name).localeCompare(normalizeCategoryValue(b.name), 'tr');
  });
}
