/**
 * Daraltılmış kategori taksonomisi.
 *
 * - PRIMARY: sitede listelenen ~24 ana kategori
 * - GROUPS: ana kategorilerin üst grupları (UI / keşif)
 * - MERGE_MAP: eski mikro/alias slug → primary slug
 * - KEYWORDS: araç yeniden sınıflandırma için anahtar kelimeler
 */

/** @typedef {{ name: string, slug: string, group: string, iconKey: string, colorKey: string, description: string }} PrimaryCategory */

/** @type {PrimaryCategory[]} */
export const PRIMARY_CATEGORIES = [
  {
    name: 'Görsel Üretim',
    slug: 'gorsel-uretim',
    group: 'medya',
    iconKey: 'ImagePlus',
    colorKey: 'fuchsia',
    description: 'Metinden görsel, illüstrasyon ve yaratıcı imaj üretimi.',
  },
  {
    name: 'Video & Animasyon',
    slug: 'video-uretim',
    group: 'medya',
    iconKey: 'Film',
    colorKey: 'red',
    description: 'AI video üretimi, montaj, animasyon ve motion tools.',
  },
  {
    name: 'Ses & Müzik',
    slug: 'ses-muzik',
    group: 'medya',
    iconKey: 'Music',
    colorKey: 'rose',
    description: 'Müzik üretimi, ses klonlama, podcast ve ses stüdyosu.',
  },
  {
    name: '3D & Avatar',
    slug: '3d-modelleme',
    group: 'medya',
    iconKey: 'Box',
    colorKey: 'teal',
    description: '3D model, dijital insan, avatar ve sanal sahne araçları.',
  },
  {
    name: 'Tasarım',
    slug: 'tasarim',
    group: 'medya',
    iconKey: 'Palette',
    colorKey: 'pink',
    description: 'UI/UX, logo, grafik tasarım ve yaratıcı iş akışları.',
  },
  {
    name: 'Metin & Yazım',
    slug: 'metin-yazarligi',
    group: 'icerik',
    iconKey: 'PenTool',
    colorKey: 'green',
    description: 'Blog, kopya, senaryo, çeviri ve dil düzenleme araçları.',
  },
  {
    name: 'Pazarlama & SEO',
    slug: 'pazarlama',
    group: 'icerik',
    iconKey: 'Megaphone',
    colorKey: 'orange',
    description: 'SEO, reklam, sosyal medya ve kampanya optimizasyonu.',
  },
  {
    name: 'Kod & Geliştirici',
    slug: 'kod-yazilim',
    group: 'gelistirme',
    iconKey: 'Code2',
    colorKey: 'blue',
    description: 'Kod asistanları, dev araçları, test ve API çözümleri.',
  },
  {
    name: 'No-Code / Low-Code',
    slug: 'no-code-low-code',
    group: 'gelistirme',
    iconKey: 'LayoutTemplate',
    colorKey: 'amber',
    description: 'Kod yazmadan uygulama, form ve otomasyon kurma.',
  },
  {
    name: 'Veri & Analitik',
    slug: 'veri-analiz',
    group: 'gelistirme',
    iconKey: 'BarChart3',
    colorKey: 'emerald',
    description: 'Veri analizi, BI, SQL ve tahminleme araçları.',
  },
  {
    name: 'Otomasyon & Ajanlar',
    slug: 'otomasyon-ajan',
    group: 'gelistirme',
    iconKey: 'Workflow',
    colorKey: 'indigo',
    description: 'Otonom ajanlar, iş akışı ve süreç otomasyonu.',
  },
  {
    name: 'Chatbot & Asistan',
    slug: 'chatbotlar',
    group: 'is',
    iconKey: 'MessageSquare',
    colorKey: 'violet',
    description: 'Sohbet botları, kişisel asistanlar ve multimodal LLM arayüzleri.',
  },
  {
    name: 'Üretkenlik',
    slug: 'uretkenlik',
    group: 'is',
    iconKey: 'Zap',
    colorKey: 'yellow',
    description: 'Not, toplantı, görev ve günlük verimlilik asistanları.',
  },
  {
    name: 'Satış & CRM',
    slug: 'satis-crm',
    group: 'is',
    iconKey: 'ShoppingCart',
    colorKey: 'orange',
    description: 'Lead, pipeline, satış tahmin ve CRM otomasyonu.',
  },
  {
    name: 'E-Ticaret',
    slug: 'e-ticaret',
    group: 'is',
    iconKey: 'Store',
    colorKey: 'emerald',
    description: 'Ürün açıklaması, mağaza optimizasyonu ve e-ticaret AI.',
  },
  {
    name: 'Müşteri Destek',
    slug: 'musteri-destek',
    group: 'is',
    iconKey: 'Headset',
    colorKey: 'blue',
    description: 'Destek botu, ticket ve canlı sohbet otomasyonu.',
  },
  {
    name: 'İş & Finans',
    slug: 'is-dunyasi',
    group: 'is',
    iconKey: 'Briefcase',
    colorKey: 'slate',
    description: 'Finans, muhasebe, operasyon ve iş planlama AI.',
  },
  {
    name: 'İnsan Kaynakları',
    slug: 'insan-kaynaklari',
    group: 'is',
    iconKey: 'UserCog',
    colorKey: 'teal',
    description: 'İşe alım, CV tarama ve İK süreç araçları.',
  },
  {
    name: 'Hukuk & Uyumluluk',
    slug: 'hukuk-uyumluluk',
    group: 'is',
    iconKey: 'Scale',
    colorKey: 'stone',
    description: 'Sözleşme inceleme, yasal araştırma ve uyumluluk.',
  },
  {
    name: 'Güvenlik & Siber',
    slug: 'guvenlik-siber',
    group: 'is',
    iconKey: 'Shield',
    colorKey: 'red',
    description: 'Tehdit tespiti, fraud ve siber güvenlik AI.',
  },
  {
    name: 'Eğitim',
    slug: 'egitim',
    group: 'yasam',
    iconKey: 'GraduationCap',
    colorKey: 'indigo',
    description: 'Öğrenme, sınav, dil pratiği ve eğitim asistanları.',
  },
  {
    name: 'Araştırma & Akademik',
    slug: 'arastirma-akademik',
    group: 'yasam',
    iconKey: 'Telescope',
    colorKey: 'indigo',
    description: 'Akademik arama, makale ve bilimsel keşif araçları.',
  },
  {
    name: 'Sağlık & Yaşam',
    slug: 'saglik-yasam',
    group: 'yasam',
    iconKey: 'HeartPulse',
    colorKey: 'rose',
    description: 'Sağlık, fitness, beslenme ve wellness AI.',
  },
  {
    name: 'Oyun & Eğlence',
    slug: 'oyun-eglence',
    group: 'yasam',
    iconKey: 'Gamepad2',
    colorKey: 'violet',
    description: 'Oyun asset, NPC, film/dizi ve eğlence AI.',
  },
  {
    name: 'Diğer',
    slug: 'diger',
    group: 'diger',
    iconKey: 'Layers',
    colorKey: 'slate',
    description: 'Yukarıdaki gruplara sığmayan yenilikçi AI araçları.',
  },
];

export const CATEGORY_GROUPS = [
  {
    id: 'medya',
    name: 'Medya & Yaratım',
    description: 'Görsel, video, ses, 3D ve tasarım araçları',
    slugs: ['gorsel-uretim', 'video-uretim', 'ses-muzik', '3d-modelleme', 'tasarim'],
  },
  {
    id: 'icerik',
    name: 'İçerik & Büyüme',
    description: 'Yazım, pazarlama ve SEO',
    slugs: ['metin-yazarligi', 'pazarlama'],
  },
  {
    id: 'gelistirme',
    name: 'Geliştirme & Veri',
    description: 'Kod, no-code, veri ve otomasyon',
    slugs: ['kod-yazilim', 'no-code-low-code', 'veri-analiz', 'otomasyon-ajan'],
  },
  {
    id: 'is',
    name: 'İş & Operasyon',
    description: 'Asistan, satış, destek, finans ve güvenlik',
    slugs: [
      'chatbotlar',
      'uretkenlik',
      'satis-crm',
      'e-ticaret',
      'musteri-destek',
      'is-dunyasi',
      'insan-kaynaklari',
      'hukuk-uyumluluk',
      'guvenlik-siber',
    ],
  },
  {
    id: 'yasam',
    name: 'Yaşam & Öğrenme',
    description: 'Eğitim, araştırma, sağlık ve eğlence',
    slugs: ['egitim', 'arastirma-akademik', 'saglik-yasam', 'oyun-eglence'],
  },
  {
    id: 'diger',
    name: 'Diğer',
    description: 'Sınıflandırılamayan araçlar',
    slugs: ['diger'],
  },
];

/**
 * Eski / mikro kategori slug → primary slug.
 * Bir üst kategori diğerlerini “içinde barındırır”.
 */
export const CATEGORY_MERGE_MAP = {
  // Görsel
  'gorsel-video': 'gorsel-uretim',
  'gorsel-uretim': 'gorsel-uretim',
  'fotograf-duzenleme': 'gorsel-uretim',
  'gorsel-iyilestirme': 'gorsel-uretim',
  'arka-plan-kaldirma': 'gorsel-uretim',
  'thumbnail-kapak': 'gorsel-uretim',
  'urun-fotograf': 'gorsel-uretim',
  // Video
  'video-uretim': 'video-uretim',
  'motion-graphics': 'video-uretim',
  storyboard: 'video-uretim',
  'film-dizi': 'video-uretim',
  streaming: 'video-uretim',
  yayincilik: 'video-uretim',
  // Ses
  'ses-muzik': 'ses-muzik',
  'ses-klonlama': 'ses-muzik',
  'podcast-yayin': 'ses-muzik',
  'muzik-uretim': 'ses-muzik',
  'ses-efektleri': 'ses-muzik',
  'ses-temizleme': 'ses-muzik',
  'sarki-sozu': 'ses-muzik',
  'radyo-yayin': 'ses-muzik',
  'enstruman-ai': 'ses-muzik',
  'dj-mix': 'ses-muzik',
  'sesli-asistan': 'ses-muzik',
  // 3D
  '3d-modelleme': '3d-modelleme',
  '3d-animasyon': '3d-modelleme',
  'avatar-dijital-insan': '3d-modelleme',
  // Tasarım
  tasarim: 'tasarim',
  tasarm: 'tasarim',
  'logo-marka': 'tasarim',
  'ui-ux-tasarim': 'tasarim',
  'ic-mimarlik': 'tasarim',
  moda: 'tasarim',
  // Metin
  'metin-yazarligi': 'metin-yazarligi',
  'metin-icerik': 'metin-yazarligi',
  'ceviri-dil': 'metin-yazarligi',
  'kopya-yazarligi': 'metin-yazarligi',
  'senaryo-yazimi': 'metin-yazarligi',
  'hikaye-roman': 'metin-yazarligi',
  ozetleme: 'metin-yazarligi',
  'dilbilgisi-duzenleme': 'metin-yazarligi',
  transkripsiyon: 'metin-yazarligi',
  altyazi: 'metin-yazarligi',
  'sunum-dokuman': 'metin-yazarligi',
  'e-posta-yazimi': 'metin-yazarligi',
  'haber-gazetecilik': 'metin-yazarligi',
  'akademik-yazim': 'metin-yazarligi',
  'prompt-muhendisligi': 'metin-yazarligi',
  // Pazarlama
  pazarlama: 'pazarlama',
  'sosyal-medya': 'pazarlama',
  seo: 'pazarlama',
  'reklam-performance': 'pazarlama',
  influencer: 'pazarlama',
  'e-posta-pazarlama': 'pazarlama',
  'pazar-arastirmasi': 'pazarlama',
  'itibar-yonetimi': 'pazarlama',
  'paylasim-viral': 'pazarlama',
  'icerik-takvimi': 'pazarlama',
  'ab-test': 'pazarlama',
  'musteri-yolculugu': 'pazarlama',
  // Kod
  'kod-yazilim': 'kod-yazilim',
  'gelistirici-araclari': 'kod-yazilim',
  'mlops-model': 'kod-yazilim',
  'veritabani-bilgi': 'kod-yazilim',
  'api-entegrasyon': 'kod-yazilim',
  'test-qa': 'kod-yazilim',
  'devops-bulut': 'kod-yazilim',
  'guvenlik-kod': 'kod-yazilim',
  'mobil-gelistirme': 'kod-yazilim',
  'web-gelistirme': 'kod-yazilim',
  'veri-bilimi': 'veri-analiz',
  'sql-veri': 'veri-analiz',
  'kod-inceleme': 'kod-yazilim',
  'dokumantasyon-kod': 'kod-yazilim',
  'terminal-cli': 'kod-yazilim',
  'donanim-iot': 'kod-yazilim',
  'yari-iletken-chip': 'kod-yazilim',
  // No-code
  'no-code-low-code': 'no-code-low-code',
  // Veri
  'veri-analiz': 'veri-analiz',
  'analitik-dashboard': 'veri-analiz',
  'is-zekasi': 'veri-analiz',
  tahminleme: 'veri-analiz',
  kisisellestirme: 'veri-analiz',
  // Otomasyon
  'otomasyon-ajan': 'otomasyon-ajan',
  // Chatbot
  chatbotlar: 'chatbotlar',
  'multimodal-asistanlar': 'chatbotlar',
  'kurumsal-chatbot': 'chatbotlar',
  'kisisel-asistan': 'chatbotlar',
  'arama-motoru': 'chatbotlar',
  'arama-deneyimi': 'chatbotlar',
  // Üretkenlik
  uretkenlik: 'uretkenlik',
  verimlilik: 'uretkenlik',
  'toplanti-not': 'uretkenlik',
  'bilgi-yonetimi': 'uretkenlik',
  'gorev-yonetimi': 'uretkenlik',
  'takvim-zaman': 'uretkenlik',
  'not-alma': 'uretkenlik',
  'form-anket': 'uretkenlik',
  isbirligi: 'uretkenlik',
  'bilgi-bankasi': 'uretkenlik',
  'belge-soru-cevap': 'uretkenlik',
  // Satış
  'satis-crm': 'satis-crm',
  'crm-pipeline': 'satis-crm',
  // E-ticaret
  'e-ticaret': 'e-ticaret',
  fiyatlandirma: 'e-ticaret',
  // Destek
  'musteri-destek': 'musteri-destek',
  'canli-sohbet': 'musteri-destek',
  'topluluk-yonetimi': 'musteri-destek',
  // İş
  'is-dunyasi': 'is-dunyasi',
  'finans-yatirim': 'is-dunyasi',
  muhasebe: 'is-dunyasi',
  'butce-harcama': 'is-dunyasi',
  'urun-yonetimi': 'is-dunyasi',
  girisimcilik: 'is-dunyasi',
  danismanlik: 'is-dunyasi',
  operasyon: 'is-dunyasi',
  'tedarik-zinciri': 'is-dunyasi',
  'depo-envanter': 'is-dunyasi',
  lojistik: 'is-dunyasi',
  sigorta: 'is-dunyasi',
  bankacilik: 'is-dunyasi',
  'kripto-web3': 'is-dunyasi',
  emlak: 'is-dunyasi',
  'emlak-insaat': 'is-dunyasi',
  seyahat: 'is-dunyasi',
  'otel-konaklama': 'is-dunyasi',
  otomotiv: 'is-dunyasi',
  tarim: 'is-dunyasi',
  'iklim-enerji': 'is-dunyasi',
  cevre: 'is-dunyasi',
  inovasyon: 'is-dunyasi',
  // İK
  'insan-kaynaklari': 'insan-kaynaklari',
  'cv-kariyer': 'insan-kaynaklari',
  // Hukuk
  'hukuk-uyumluluk': 'hukuk-uyumluluk',
  'sozlesme-inceleme': 'hukuk-uyumluluk',
  'hukuk-burosu': 'hukuk-uyumluluk',
  // Güvenlik
  'guvenlik-siber': 'guvenlik-siber',
  'kimlik-fraud': 'guvenlik-siber',
  'icerik-moderasyon': 'guvenlik-siber',
  // Eğitim
  egitim: 'egitim',
  'dil-ogrenme': 'egitim',
  'sinav-hazirlik': 'egitim',
  'cocuk-ebeveyn': 'egitim',
  // Araştırma
  'arastirma-akademik': 'arastirma-akademik',
  'web-arastirma': 'arastirma-akademik',
  'bilim-lab': 'arastirma-akademik',
  'kimya-malzeme': 'arastirma-akademik',
  uzay: 'arastirma-akademik',
  // Sağlık
  'saglik-yasam': 'saglik-yasam',
  'saglikli-yasam': 'saglik-yasam',
  fitness: 'saglik-yasam',
  beslenme: 'saglik-yasam',
  'mental-saglik': 'saglik-yasam',
  erisilebilirlik: 'saglik-yasam',
  hayirseverlik: 'saglik-yasam',
  guzellik: 'saglik-yasam',
  'yemek-mutfak': 'saglik-yasam',
  'sarap-icecek': 'saglik-yasam',
  'evcil-hayvan': 'saglik-yasam',
  spor: 'saglik-yasam',
  // Oyun
  'oyun-eglence': 'oyun-eglence',
  'oyun-hikayesi': 'oyun-eglence',
  'oyun-asset': 'oyun-eglence',
  // Diğer
  diger: 'diger',
  'qr-barkod': 'diger',
  'harita-konum': 'diger',
  savunma: 'diger',
};

/** Bilinen araç adı → primary slug (yüksek öncelik) */
export const KNOWN_TOOL_CATEGORIES = {
  midjourney: 'gorsel-uretim',
  'dall-e': 'gorsel-uretim',
  'dall·e': 'gorsel-uretim',
  'stable diffusion': 'gorsel-uretim',
  'leonardo ai': 'gorsel-uretim',
  ideogram: 'gorsel-uretim',
  'seaart ai': 'gorsel-uretim',
  runway: 'video-uretim',
  'runway ml': 'video-uretim',
  pika: 'video-uretim',
  'pika labs': 'video-uretim',
  kaiber: 'video-uretim',
  synthesia: 'video-uretim',
  heygen: 'video-uretim',
  kling: 'video-uretim',
  luma: 'video-uretim',
  'luma ai': 'video-uretim',
  sora: 'video-uretim',
  elevenlabs: 'ses-muzik',
  suno: 'ses-muzik',
  udio: 'ses-muzik',
  descript: 'ses-muzik',
  'murf ai': 'ses-muzik',
  chatgpt: 'chatbotlar',
  'chat gpt': 'chatbotlar',
  claude: 'chatbotlar',
  'google gemini': 'chatbotlar',
  gemini: 'chatbotlar',
  perplexity: 'chatbotlar',
  'character.ai': 'chatbotlar',
  grok: 'chatbotlar',
  poe: 'chatbotlar',
  'github copilot': 'kod-yazilim',
  cursor: 'kod-yazilim',
  replit: 'kod-yazilim',
  tabnine: 'kod-yazilim',
  codeium: 'kod-yazilim',
  windsurf: 'kod-yazilim',
  'notion ai': 'uretkenlik',
  notion: 'uretkenlik',
  otter: 'uretkenlik',
  'otter.ai': 'uretkenlik',
  fireflies: 'uretkenlik',
  quillbot: 'metin-yazarligi',
  jasper: 'metin-yazarligi',
  'copy.ai': 'metin-yazarligi',
  grammarly: 'metin-yazarligi',
  duolingo: 'egitim',
  khanmigo: 'egitim',
  canva: 'tasarim',
  figma: 'tasarim',
  uizard: 'tasarim',
  zapier: 'otomasyon-ajan',
  make: 'otomasyon-ajan',
  n8n: 'otomasyon-ajan',
  hubspot: 'satis-crm',
  intercom: 'musteri-destek',
  zendesk: 'musteri-destek',
};

/** @type {Record<string, string[]>} */
export const CATEGORY_KEYWORDS = {
  'gorsel-uretim': [
    'image',
    'görsel',
    'gorsel',
    'midjourney',
    'dall',
    'stable diffusion',
    'photo',
    'foto',
    'illustration',
    'upscale',
    'background remov',
    'arka plan',
    'logo generator',
    'text to image',
    'metinden görsel',
    'image generator',
    'görüntü',
  ],
  'video-uretim': [
    'video',
    'runway',
    'pika',
    'sora',
    'kling',
    'luma',
    'kaiber',
    'synthesia',
    'heygen',
    'animat',
    'motion graphic',
    'film',
    'editing',
    'montaj',
    'text to video',
    'video üret',
    'video generat',
  ],
  'ses-muzik': [
    'music',
    'müzik',
    'muzik',
    'audio',
    'ses',
    'voice',
    'tts',
    'speech',
    'podcast',
    'elevenlabs',
    'suno',
    'udio',
    'klonlama',
    'şarkı',
    'sarki',
  ],
  '3d-modelleme': [
    '3d',
    'avatar',
    'mesh',
    'nerf',
    'digital human',
    'talking head',
    'blender',
    'modelleme',
  ],
  tasarim: [
    'design',
    'tasarım',
    'tasarim',
    'figma',
    'ui ',
    'ux ',
    'canva',
    'wireframe',
    'mockup',
    'brand',
    'marka',
  ],
  'metin-yazarligi': [
    'writing',
    'yaz',
    'copy',
    'blog',
    'grammar',
    'dilbilgi',
    'translate',
    'çeviri',
    'ceviri',
    'paraphras',
    'summar',
    'özet',
    'ozet',
    'jasper',
    'copy.ai',
    'quillbot',
    'notion ai',
    'document',
    'metin',
  ],
  pazarlama: [
    'market',
    'pazarlama',
    'seo',
    'ads',
    'reklam',
    'social media',
    'sosyal medya',
    'campaign',
    'kampanya',
    'influencer',
    'newsletter',
    'growth',
  ],
  'kod-yazilim': [
    'code',
    'kod',
    'developer',
    'github',
    'copilot',
    'ide',
    'api',
    'debug',
    'programming',
    'yazılım',
    'yazilim',
    'devops',
    'sql',
    'cursor',
  ],
  'no-code-low-code': [
    'no-code',
    'nocode',
    'low-code',
    'lowcode',
    'bubble',
    'webflow',
    'zapier',
    'make.com',
    'kodsuz',
  ],
  'veri-analiz': [
    'data',
    'veri',
    'analytics',
    'analitik',
    'dashboard',
    'bi ',
    'chart',
    'forecast',
    'tahmin',
    'excel',
    'spreadsheet',
  ],
  'otomasyon-ajan': [
    'agent',
    'ajan',
    'automat',
    'otomasyon',
    'workflow',
    'rpa',
    'orchestr',
    'multi-agent',
  ],
  chatbotlar: [
    'chat',
    'gpt',
    'claude',
    'gemini',
    'llm',
    'assistant',
    'asistan',
    'chatbot',
    'conversat',
    'perplexity',
    'character.ai',
  ],
  uretkenlik: [
    'productiv',
    'verimlilik',
    'üretkenlik',
    'uretkenlik',
    'note',
    'not ',
    'meeting',
    'toplantı',
    'toplanti',
    'todo',
    'calendar',
    'takvim',
    'notion',
    'obsidian',
  ],
  'satis-crm': ['sales', 'satış', 'satis', 'crm', 'lead', 'pipeline', 'outreach', 'cold email'],
  'e-ticaret': [
    'ecommerce',
    'e-commerce',
    'e-ticaret',
    'eticaret',
    'shopify',
    'product description',
    'ürün',
    'magaza',
    'mağaza',
  ],
  'musteri-destek': [
    'support',
    'destek',
    'helpdesk',
    'ticket',
    'customer service',
    'müşteri hizmet',
    'zendesk',
    'intercom',
  ],
  'is-dunyasi': [
    'finance',
    'finans',
    'accounting',
    'muhasebe',
    'invoice',
    'budget',
    'business',
    'iş ',
    'startup',
    'pitch',
    'invest',
    'crypto',
    'bank',
  ],
  'insan-kaynaklari': [
    'hr ',
    'hiring',
    'recruit',
    'işe alım',
    'cv ',
    'resume',
    'talent',
    'ik ',
    'human resource',
  ],
  'hukuk-uyumluluk': [
    'legal',
    'hukuk',
    'contract',
    'sözleşme',
    'sozlesme',
    'compliance',
    'uyumluluk',
    'law',
  ],
  'guvenlik-siber': [
    'security',
    'güvenlik',
    'guvenlik',
    'cyber',
    'siber',
    'fraud',
    'malware',
    'vulnerability',
    'threat',
  ],
  egitim: [
    'educat',
    'eğitim',
    'egitim',
    'learn',
    'öğren',
    'ogren',
    'tutor',
    'course',
    'kurs',
    'exam',
    'sınav',
    'sinav',
    'language learn',
  ],
  'arastirma-akademik': [
    'research',
    'araştırma',
    'arastirma',
    'academic',
    'akademik',
    'paper',
    'scholar',
    'science',
    'bilim',
    'citation',
  ],
  'saglik-yasam': [
    'health',
    'sağlık',
    'saglik',
    'fitness',
    'wellness',
    'nutrition',
    'beslenme',
    'mental',
    'medikal',
    'medical',
    'diet',
  ],
  'oyun-eglence': [
    'game',
    'oyun',
    'npc',
    'unity',
    'unreal',
    'entertainment',
    'eğlence',
    'eglence',
    'rpg',
  ],
  diger: [],
};

export const PRIMARY_SLUGS = new Set(PRIMARY_CATEGORIES.map((c) => c.slug));

export function resolvePrimarySlug(slugOrName) {
  if (!slugOrName) return 'diger';
  const raw = String(slugOrName).trim();
  const asSlug = raw
    .toLocaleLowerCase('tr-TR')
    .replaceAll('ğ', 'g')
    .replaceAll('ü', 'u')
    .replaceAll('ş', 's')
    .replaceAll('ı', 'i')
    .replaceAll('ö', 'o')
    .replaceAll('ç', 'c')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (CATEGORY_MERGE_MAP[asSlug]) return CATEGORY_MERGE_MAP[asSlug];
  if (PRIMARY_SLUGS.has(asSlug)) return asSlug;
  if (CATEGORY_MERGE_MAP[raw]) return CATEGORY_MERGE_MAP[raw];
  return null;
}

/**
 * İsim + açıklama ile en uygun primary slug tahmini.
 * @returns {{ slug: string, score: number, matched: string[] }}
 */
export function classifyToolText(name = '', description = '', link = '') {
  const nameKey = String(name || '')
    .toLocaleLowerCase('tr-TR')
    .trim();

  for (const [known, slug] of Object.entries(KNOWN_TOOL_CATEGORIES)) {
    if (nameKey === known || nameKey.includes(known)) {
      return { slug, score: 20, matched: [`known:${known}`] };
    }
  }

  const haystack = `${name} ${description} ${link}`.toLocaleLowerCase('tr-TR');
  let best = { slug: 'diger', score: 0, matched: [] };

  for (const [slug, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (slug === 'diger') continue;
    const matched = [];
    let score = 0;
    for (const kw of keywords) {
      if (haystack.includes(kw.toLocaleLowerCase('tr-TR'))) {
        matched.push(kw);
        // longer / more specific keywords weigh more
        score += Math.max(1, Math.min(4, Math.ceil(kw.length / 6)));
      }
    }
    if (score > best.score) {
      best = { slug, score, matched };
    }
  }

  // weak signal → other
  if (best.score < 2) {
    return { slug: 'diger', score: best.score, matched: best.matched };
  }
  return best;
}

export function isPrimaryCategorySlug(slug) {
  return PRIMARY_SLUGS.has(slug);
}
