import {
  Image as ImageIcon,
  Code2,
  Megaphone,
  PenTool,
  Music,
  Zap,
  Palette,
  GraduationCap,
  Box,
  Search,
  MessageSquare,
  Briefcase,
  Bot,
  Video,
  Database,
  LayoutTemplate,
  Shield,
  HeartPulse,
  Scale,
  ShoppingCart,
  Gamepad2,
  Mic2,
  Film,
  Sparkles,
  LineChart,
  Workflow,
  Cpu,
  Globe2,
  Users,
  BookOpen,
  Camera,
  Headphones,
  Building2,
  Stethoscope,
  Landmark,
  Languages,
  Binary,
  Rocket,
  Layers,
  Wrench,
  Brain,
  Car,
  Plane,
  Leaf,
  Baby,
  Shirt,
  Utensils,
  Dumbbell,
  Clapperboard,
  Newspaper,
  Mail,
  Calendar,
  FileText,
  PieChart,
  BarChart3,
  Network,
  Cloud,
  Lock,
  Eye,
  Scissors,
  Paintbrush,
  Type,
  AudioLines,
  Radio,
  Podcast,
  Store,
  Truck,
  Factory,
  FlaskConical,
  Atom,
  Telescope,
  School,
  University,
  Handshake,
  Target,
  TrendingUp,
  Wallet,
  Receipt,
  Gavel,
  Fingerprint,
  Bug,
  Server,
  Terminal,
  Braces,
  GitBranch,
  AppWindow,
  Smartphone,
  Watch,
  Home,
  Trees,
  Mountain,
  Ship,
  Bike,
  Church,
  PawPrint,
  Flower2,
  Coffee,
  Wine,
  Hotel,
  MapPin,
  Compass,
  Lightbulb,
  Puzzle,
  Timer,
  ListTodo,
  StickyNote,
  Presentation,
  Table,
  FormInput,
  QrCode,
  Share2,
  Hash,
  AtSign,
  MessagesSquare,
  PhoneCall,
  Headset,
  UserCog,
  IdCard,
  BadgeCheck,
  Package,
  Boxes,
  Warehouse,
  Recycle,
  Wind,
  Sun,
  Droplets,
  Flame,
  Snowflake,
  Accessibility,
  HandHeart,
  Smile,
  Drama,
  Music2,
  Piano,
  Guitar,
  Disc3,
  ImagePlus,
  Images,
  Aperture,
  Focus,
  Crop,
  Wand2,
  Blend,
  Shapes,
  Cuboid,
  Orbit,
  CircuitBoard,
  Microchip,
  BotMessageSquare,
  Speech,
  Captions,
  Subtitles,
  ScanText,
  FileSearch,
  FolderSearch,
  Library,
  ScrollText,
  NotebookPen,
  PenLine,
  Quote,
  SpellCheck,
  WholeWord,
  Sigma,
  Calculator,
  ChartSpline,
  Activity,
  Crosshair,
  Swords,
  Trophy,
  Dices,
  Joystick,
  Popcorn,
  Tv,
  MonitorPlay,
  Webcam,
  Printer,
  HardDrive,
  Usb,
  Wifi,
  Bluetooth,
  BatteryCharging,
  Plug,
  Cable,
} from 'lucide-react';
import { normalizeCategoryLookupKey } from '@/lib/categoryLookup';

const ICONS = {
  ImageIcon,
  Code2,
  Megaphone,
  PenTool,
  Music,
  Zap,
  Palette,
  GraduationCap,
  Box,
  Search,
  MessageSquare,
  Briefcase,
  Bot,
  Video,
  Database,
  LayoutTemplate,
  Shield,
  HeartPulse,
  Scale,
  ShoppingCart,
  Gamepad2,
  Mic2,
  Film,
  Sparkles,
  LineChart,
  Workflow,
  Cpu,
  Globe2,
  Users,
  BookOpen,
  Camera,
  Headphones,
  Building2,
  Stethoscope,
  Landmark,
  Languages,
  Binary,
  Rocket,
  Layers,
  Wrench,
  Brain,
  Car,
  Plane,
  Leaf,
  Baby,
  Shirt,
  Utensils,
  Dumbbell,
  Clapperboard,
  Newspaper,
  Mail,
  Calendar,
  FileText,
  PieChart,
  BarChart3,
  Network,
  Cloud,
  Lock,
  Eye,
  Scissors,
  Paintbrush,
  Type,
  AudioLines,
  Radio,
  Podcast,
  Store,
  Truck,
  Factory,
  FlaskConical,
  Atom,
  Telescope,
  School,
  University,
  Handshake,
  Target,
  TrendingUp,
  Wallet,
  Receipt,
  Gavel,
  Fingerprint,
  Bug,
  Server,
  Terminal,
  Braces,
  GitBranch,
  AppWindow,
  Smartphone,
  Watch,
  Home,
  Trees,
  Mountain,
  Ship,
  Bike,
  Church,
  PawPrint,
  Flower2,
  Coffee,
  Wine,
  Hotel,
  MapPin,
  Compass,
  Lightbulb,
  Puzzle,
  Timer,
  ListTodo,
  StickyNote,
  Presentation,
  Table,
  FormInput,
  QrCode,
  Share2,
  Hash,
  AtSign,
  MessagesSquare,
  PhoneCall,
  Headset,
  UserCog,
  IdCard,
  BadgeCheck,
  Package,
  Boxes,
  Warehouse,
  Recycle,
  Wind,
  Sun,
  Droplets,
  Flame,
  Snowflake,
  Accessibility,
  HandHeart,
  Smile,
  Drama,
  Music2,
  Piano,
  Guitar,
  Disc3,
  ImagePlus,
  Images,
  Aperture,
  Focus,
  Crop,
  Wand2,
  Blend,
  Shapes,
  Cuboid,
  Orbit,
  CircuitBoard,
  Microchip,
  BotMessageSquare,
  Speech,
  Captions,
  Subtitles,
  ScanText,
  FileSearch,
  FolderSearch,
  Library,
  ScrollText,
  NotebookPen,
  PenLine,
  Quote,
  SpellCheck,
  WholeWord,
  Sigma,
  Calculator,
  ChartSpline,
  Activity,
  Crosshair,
  Swords,
  Trophy,
  Dices,
  Joystick,
  Popcorn,
  Tv,
  MonitorPlay,
  Webcam,
  Printer,
  HardDrive,
  Usb,
  Wifi,
  Bluetooth,
  BatteryCharging,
  Plug,
  Cable,
  LayoutTemplate,
};

const COLORS = {
  purple: {
    color: 'purple',
    gradient: 'from-purple-500/20 to-fuchsia-500/20',
    border: 'border-purple-500/30',
    text: 'text-purple-500',
  },
  blue: {
    color: 'blue',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
  },
  orange: {
    color: 'orange',
    gradient: 'from-orange-500/20 to-amber-500/20',
    border: 'border-orange-500/30',
    text: 'text-orange-500',
  },
  green: {
    color: 'green',
    gradient: 'from-green-500/20 to-emerald-500/20',
    border: 'border-green-500/30',
    text: 'text-green-500',
  },
  rose: {
    color: 'rose',
    gradient: 'from-rose-500/20 to-pink-500/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
  },
  yellow: {
    color: 'yellow',
    gradient: 'from-yellow-500/20 to-amber-400/20',
    border: 'border-yellow-500/30',
    text: 'text-yellow-500',
  },
  pink: {
    color: 'pink',
    gradient: 'from-pink-500/20 to-rose-400/20',
    border: 'border-pink-500/30',
    text: 'text-pink-500',
  },
  indigo: {
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-blue-500/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
  },
  teal: {
    color: 'teal',
    gradient: 'from-teal-500/20 to-emerald-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
  },
  cyan: {
    color: 'cyan',
    gradient: 'from-cyan-500/20 to-blue-400/20',
    border: 'border-cyan-500/30',
    text: 'text-cyan-500',
  },
  violet: {
    color: 'violet',
    gradient: 'from-violet-500/20 to-purple-500/20',
    border: 'border-violet-500/30',
    text: 'text-violet-500',
  },
  slate: {
    color: 'slate',
    gradient: 'from-slate-500/20 to-gray-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
  },
  fuchsia: {
    color: 'fuchsia',
    gradient: 'from-fuchsia-500/20 to-purple-400/20',
    border: 'border-fuchsia-500/30',
    text: 'text-fuchsia-500',
  },
  red: {
    color: 'red',
    gradient: 'from-red-500/20 to-orange-400/20',
    border: 'border-red-500/30',
    text: 'text-red-500',
  },
  amber: {
    color: 'amber',
    gradient: 'from-amber-500/20 to-yellow-400/20',
    border: 'border-amber-500/30',
    text: 'text-amber-500',
  },
  sky: {
    color: 'sky',
    gradient: 'from-sky-500/20 to-blue-400/20',
    border: 'border-sky-500/30',
    text: 'text-sky-500',
  },
  emerald: {
    color: 'emerald',
    gradient: 'from-emerald-500/20 to-teal-400/20',
    border: 'border-emerald-500/30',
    text: 'text-emerald-500',
  },
  stone: {
    color: 'stone',
    gradient: 'from-stone-500/20 to-amber-400/20',
    border: 'border-stone-500/30',
    text: 'text-stone-500',
  },
  lime: {
    color: 'lime',
    gradient: 'from-lime-500/20 to-green-400/20',
    border: 'border-lime-500/30',
    text: 'text-lime-500',
  },
};

/**
 * Tek kaynak: name, slug, iconKey, colorKey, description
 * ~120+ kategori
 */
const CATEGORY_DEFS = [
  // Medya & yaratım
  [
    'Görsel & Video',
    'gorsel-video',
    'Video',
    'purple',
    'Görsel üretimi, video düzenleme ve tasarım için AI araçları.',
  ],
  [
    'Görsel Üretim',
    'gorsel-uretim',
    'ImagePlus',
    'fuchsia',
    'Metinden görsel ve yaratıcı illüstrasyon üreten modeller.',
  ],
  [
    'Video Üretim',
    'video-uretim',
    'Film',
    'red',
    'Kısa/uzun video, animasyon ve sinematik AI video araçları.',
  ],
  [
    'Fotoğraf Düzenleme',
    'fotograf-duzenleme',
    'Camera',
    'pink',
    'Retuş, arka plan kaldırma ve fotoğraf iyileştirme.',
  ],
  [
    'Görsel İyileştirme',
    'gorsel-iyilestirme',
    'Aperture',
    'pink',
    'Upscale, netleştirme ve bozulmuş görsel onarımı.',
  ],
  [
    'Arka Plan Kaldırma',
    'arka-plan-kaldirma',
    'Focus',
    'rose',
    'Ürün ve portre için arka plan silme araçları.',
  ],
  ['Logo & Marka', 'logo-marka', 'Shapes', 'violet', 'Logo üretimi ve marka kimliği AI araçları.'],
  [
    'UI/UX Tasarım',
    'ui-ux-tasarim',
    'AppWindow',
    'indigo',
    'Arayüz mockup, wireframe ve tasarım asistanları.',
  ],
  ['Tasarım', 'tasarim', 'Palette', 'pink', 'Grafik tasarım ve yaratıcı görsel iş akışları.'],
  ['3D Modelleme', '3d-modelleme', 'Box', 'teal', 'Metin/görselden 3D model ve sahne üretimi.'],
  ['3D Animasyon', '3d-animasyon', 'Cuboid', 'cyan', 'Karakter ve nesne animasyonu AI araçları.'],
  [
    'Avatar & Dijital İnsan',
    'avatar-dijital-insan',
    'Sparkles',
    'fuchsia',
    'Talking head, sanal sunucu ve dijital avatar.',
  ],
  [
    'Motion Graphics',
    'motion-graphics',
    'Clapperboard',
    'orange',
    'Hareketli grafik ve motion design araçları.',
  ],
  ['Storyboard', 'storyboard', 'Images', 'amber', 'Video ve film için storyboard üretimi.'],
  [
    'Thumbnail & Kapak',
    'thumbnail-kapak',
    'Crop',
    'rose',
    'YouTube/thumbnail ve kapak görseli üretimi.',
  ],

  // Ses
  ['Ses & Müzik', 'ses-muzik', 'Music', 'rose', 'Müzik üretimi ve ses stüdyosu AI araçları.'],
  ['Ses Klonlama', 'ses-klonlama', 'Mic2', 'rose', 'Ses klonlama, dublaj ve konuşma sentezi.'],
  [
    'Podcast & Yayın',
    'podcast-yayin',
    'Podcast',
    'amber',
    'Podcast düzenleme, özet ve yayın otomasyonu.',
  ],
  ['Müzik Üretim', 'muzik-uretim', 'Music2', 'violet', 'Melodi, beat ve şarkı üretimi AI’ları.'],
  ['Ses Efektleri', 'ses-efektleri', 'AudioLines', 'pink', 'SFX, ambiyans ve ses efekti üretimi.'],
  ['Ses Temizleme', 'ses-temizleme', 'Headphones', 'teal', 'Gürültü azaltma ve ses restorasyonu.'],
  ['Şarkı Sözü', 'sarki-sozu', 'PenLine', 'fuchsia', 'Şarkı sözü ve melodi fikirleri için AI.'],
  ['Radyo & Yayın', 'radyo-yayin', 'Radio', 'orange', 'Yayın akışı ve radyo içerik asistanları.'],
  ['Enstrüman AI', 'enstruman-ai', 'Piano', 'indigo', 'Enstrümantal aranjman ve kompozisyon.'],
  ['DJ & Mix', 'dj-mix', 'Disc3', 'purple', 'Mix, mashup ve set planlama araçları.'],

  // Metin & dil
  [
    'Metin Yazarlığı',
    'metin-yazarligi',
    'PenTool',
    'green',
    'Blog, makale ve yaratıcı metin üretimi.',
  ],
  ['Çeviri & Dil', 'ceviri-dil', 'Languages', 'sky', 'Çeviri, yerelleştirme ve çok dilli içerik.'],
  [
    'Kopya Yazarlığı',
    'kopya-yazarligi',
    'Type',
    'emerald',
    'Reklam metni, slogan ve conversion copy.',
  ],
  [
    'Senaryo Yazımı',
    'senaryo-yazimi',
    'ScrollText',
    'violet',
    'Film, dizi ve kısa video senaryoları.',
  ],
  ['Hikâye & Roman', 'hikaye-roman', 'BookOpen', 'indigo', 'Uzun form kurgu ve yaratıcı yazarlık.'],
  ['Özetleme', 'ozetleme', 'ScanText', 'cyan', 'Belge, makale ve video özetleme.'],
  [
    'Dilbilgisi & Düzenleme',
    'dilbilgisi-duzenleme',
    'SpellCheck',
    'blue',
    'Yazım, üslup ve dilbilgisi iyileştirme.',
  ],
  ['Transkripsiyon', 'transkripsiyon', 'Captions', 'teal', 'Ses/videodan metin deşifre araçları.'],
  ['Altyazı', 'altyazi', 'Subtitles', 'sky', 'Altyazı üretimi ve senkronizasyon.'],
  [
    'Sunum & Doküman',
    'sunum-dokuman',
    'Presentation',
    'orange',
    'Sunum, teklif ve iş dokümanı üretimi.',
  ],
  ['CV & Kariyer', 'cv-kariyer', 'IdCard', 'blue', 'CV, ön yazı ve mülakat hazırlık asistanları.'],
  [
    'E-posta Yazımı',
    'e-posta-yazimi',
    'Mail',
    'sky',
    'Profesyonel e-posta ve cold outreach metinleri.',
  ],
  [
    'Haber & Gazetecilik',
    'haber-gazetecilik',
    'Newspaper',
    'slate',
    'Haber özeti, araştırma ve editöryel AI.',
  ],
  [
    'Akademik Yazım',
    'akademik-yazim',
    'University',
    'indigo',
    'Makale, tez ve akademik metin desteği.',
  ],
  [
    'Prompt Mühendisliği',
    'prompt-muhendisligi',
    'Binary',
    'purple',
    'Prompt kütüphanesi, test ve optimizasyon.',
  ],

  // Kod & teknik
  ['Kod & Yazılım', 'kod-yazilim', 'Code2', 'blue', 'Kod asistanları, hata ayıklama ve mimari AI.'],
  [
    'Geliştirici Araçları',
    'gelistirici-araclari',
    'Wrench',
    'blue',
    'API, dokümantasyon ve dev üretkenlik.',
  ],
  [
    'No-Code / Low-Code',
    'no-code-low-code',
    'LayoutTemplate',
    'amber',
    'Kod yazmadan uygulama ve otomasyon.',
  ],
  ['MLOps & Model', 'mlops-model', 'Cpu', 'slate', 'Model eğitimi, dağıtım ve MLOps.'],
  ['Veritabanı & Bilgi', 'veritabani-bilgi', 'Database', 'blue', 'Vektör DB, RAG ve bilgi tabanı.'],
  [
    'API & Entegrasyon',
    'api-entegrasyon',
    'Network',
    'cyan',
    'API tasarımı, test ve entegrasyon AI.’ları.',
  ],
  ['Test & QA', 'test-qa', 'Bug', 'red', 'Test üretimi, hata analizi ve QA otomasyonu.'],
  ['DevOps & Bulut', 'devops-bulut', 'Cloud', 'sky', 'CI/CD, altyapı ve bulut otomasyonu.'],
  ['Güvenlik Kod', 'guvenlik-kod', 'Lock', 'red', 'Kod güvenlik taraması ve zafiyet analizi.'],
  [
    'Mobil Geliştirme',
    'mobil-gelistirme',
    'Smartphone',
    'indigo',
    'Mobil uygulama kod ve UI asistanları.',
  ],
  [
    'Web Geliştirme',
    'web-gelistirme',
    'AppWindow',
    'blue',
    'Frontend/backend web geliştirme AI.’ları.',
  ],
  [
    'Veri Bilimi',
    'veri-bilimi',
    'Sigma',
    'emerald',
    'Notebook, özellik mühendisliği ve ML deneyleri.',
  ],
  ['SQL & Veri', 'sql-veri', 'Table', 'teal', 'SQL üretimi, sorgu optimizasyonu ve veri keşfi.'],
  ['Kod İnceleme', 'kod-inceleme', 'GitBranch', 'violet', 'PR inceleme ve kod kalite asistanları.'],
  [
    'Dokümantasyon Kod',
    'dokumantasyon-kod',
    'Braces',
    'slate',
    'Kod dokümantasyonu ve README üretimi.',
  ],
  ['Terminal & CLI', 'terminal-cli', 'Terminal', 'slate', 'CLI asistanları ve komut önerileri.'],
  [
    'Donanım & IoT',
    'donanim-iot',
    'CircuitBoard',
    'amber',
    'IoT, gömülü sistem ve donanım AI.’ları.',
  ],
  [
    'Yarı İletken & Chip',
    'yari-iletken-chip',
    'Microchip',
    'slate',
    'Chip tasarımı ve elektronik AI araçları.',
  ],

  // İş & verimlilik
  ['Üretkenlik', 'uretkenlik', 'Zap', 'yellow', 'Günlük iş akışı ve verimlilik asistanları.'],
  [
    'Kişisel Asistan',
    'kisisel-asistan',
    'Bot',
    'cyan',
    'Planlama, e-posta ve kişisel organizasyon.',
  ],
  [
    'Otomasyon & Ajan',
    'otomasyon-ajan',
    'Workflow',
    'indigo',
    'Otonom ajanlar ve iş akışı otomasyonu.',
  ],
  [
    'Toplantı & Not',
    'toplanti-not',
    'Mic2',
    'teal',
    'Toplantı kaydı, deşifre ve aksiyon maddeleri.',
  ],
  ['Bilgi Yönetimi', 'bilgi-yonetimi', 'Brain', 'indigo', 'Second brain, not ve bilgi grafiği.'],
  [
    'Görev Yönetimi',
    'gorev-yonetimi',
    'ListTodo',
    'blue',
    'Görev planlama ve proje takip AI.’ları.',
  ],
  ['Takvim & Zaman', 'takvim-zaman', 'Calendar', 'sky', 'Zaman bloklama ve takvim optimizasyonu.'],
  ['Not Alma', 'not-alma', 'StickyNote', 'amber', 'Akıllı not ve highlight araçları.'],
  ['Form & Anket', 'form-anket', 'FormInput', 'teal', 'Anket, form ve kullanıcı araştırması.'],
  ['İşbirliği', 'isbirligi', 'Users', 'violet', 'Ekip işbirliği ve doküman ortak çalışması.'],
  [
    'CRM & Pipeline',
    'crm-pipeline',
    'Target',
    'orange',
    'Satış pipeline ve müşteri ilişkileri AI.’ı.',
  ],

  // Pazarlama & satış
  ['Pazarlama', 'pazarlama', 'Megaphone', 'orange', 'SEO, içerik ve kampanya AI çözümleri.'],
  ['Sosyal Medya', 'sosyal-medya', 'Share2', 'sky', 'Caption, planlama ve sosyal büyüme.'],
  ['SEO', 'seo', 'TrendingUp', 'green', 'Anahtar kelime, içerik SEO ve SERP analizi.'],
  [
    'Reklam & Performance',
    'reklam-performance',
    'Crosshair',
    'red',
    'Reklam metni, teklif ve ROAS optimizasyonu.',
  ],
  ['Influencer', 'influencer', 'AtSign', 'pink', 'Influencer keşfi ve kampanya yönetimi.'],
  [
    'E-posta Pazarlama',
    'e-posta-pazarlama',
    'Mail',
    'blue',
    'Newsletter ve e-posta otomasyon AI.’ı.',
  ],
  ['Satış & CRM', 'satis-crm', 'ShoppingCart', 'orange', 'Lead skorlama ve satış tahminleme.'],
  ['E-Ticaret', 'e-ticaret', 'Store', 'emerald', 'Ürün açıklaması ve mağaza optimizasyonu.'],
  ['Ürün Fotoğrafı', 'urun-fotograf', 'Camera', 'fuchsia', 'Ürün görseli ve sanal stüdyo AI.’ı.'],
  ['Fiyatlandırma', 'fiyatlandirma', 'Receipt', 'amber', 'Dinamik fiyat ve rekabet analizi.'],
  ['Müşteri Destek', 'musteri-destek', 'Headset', 'blue', 'Destek botu ve ticket otomasyonu.'],
  ['Canlı Sohbet', 'canli-sohbet', 'MessagesSquare', 'cyan', 'Web sitesi sohbet ve lead yakalama.'],
  ['İtibar Yönetimi', 'itibar-yonetimi', 'BadgeCheck', 'slate', 'Yorum analizi ve marka itibarı.'],
  [
    'Pazar Araştırması',
    'pazar-arastirmasi',
    'PieChart',
    'indigo',
    'Pazar ve rakip analiz araçları.',
  ],

  // İş dünyası
  ['İş Dünyası', 'is-dunyasi', 'Briefcase', 'slate', 'Yönetim, finans ve iş planlama AI.’ı.'],
  [
    'Finans & Yatırım',
    'finans-yatirim',
    'Landmark',
    'green',
    'Finansal analiz ve yatırım desteği.',
  ],
  ['Muhasebe', 'muhasebe', 'Calculator', 'emerald', 'Fatura, gider ve muhasebe otomasyonu.'],
  ['Bütçe & Harcama', 'butce-harcama', 'Wallet', 'lime', 'Kişisel/kurumsal bütçe asistanları.'],
  [
    'İnsan Kaynakları',
    'insan-kaynaklari',
    'UserCog',
    'teal',
    'İşe alım, CV tarama ve İK otomasyonu.',
  ],
  [
    'Hukuk & Uyumluluk',
    'hukuk-uyumluluk',
    'Scale',
    'slate',
    'Sözleşme ve yasal araştırma asistanları.',
  ],
  ['Sözleşme İnceleme', 'sozlesme-inceleme', 'Gavel', 'stone', 'Sözleşme analizi ve risk tespiti.'],
  ['Güvenlik & Siber', 'guvenlik-siber', 'Shield', 'red', 'Tehdit tespiti ve siber savunma.'],
  [
    'Kimlik & Fraud',
    'kimlik-fraud',
    'Fingerprint',
    'rose',
    'Kimlik doğrulama ve dolandırıcılık tespiti.',
  ],
  [
    'İçerik Moderasyon',
    'icerik-moderasyon',
    'Eye',
    'slate',
    'Toksisite ve içerik güvenlik filtreleri.',
  ],
  ['Ürün Yönetimi', 'urun-yonetimi', 'Layers', 'cyan', 'Roadmap, araştırma ve ürün keşfi.'],
  ['Girişimcilik', 'girisimcilik', 'Rocket', 'violet', 'İş fikri, pitch ve büyüme stratejisi.'],
  ['Danışmanlık', 'danismanlik', 'Handshake', 'blue', 'İş danışmanlığı ve strateji asistanları.'],
  ['Operasyon', 'operasyon', 'Factory', 'stone', 'Operasyonel verimlilik ve süreç AI.’ı.'],
  ['Tedarik Zinciri', 'tedarik-zinciri', 'Truck', 'amber', 'Lojistik ve stok optimizasyonu.'],
  ['Depo & Envanter', 'depo-envanter', 'Warehouse', 'slate', 'Envanter tahmin ve depo yönetimi.'],

  // Chat & asistan
  [
    'Chatbotlar',
    'chatbotlar',
    'MessageSquare',
    'violet',
    'Doğal dil sohbet robotları ve asistanlar.',
  ],
  [
    'Kurumsal Chatbot',
    'kurumsal-chatbot',
    'BotMessageSquare',
    'indigo',
    'Şirket içi bilgi chatbotları.',
  ],
  ['Sesli Asistan', 'sesli-asistan', 'Speech', 'cyan', 'Sesli komut ve konuşma asistanları.'],
  ['Arama Motoru', 'arama-motoru', 'Search', 'cyan', 'AI arama ve diyalog tabanlı discovery.'],
  [
    'Araştırma & Akademik',
    'arastirma-akademik',
    'Telescope',
    'indigo',
    'Akademik arama ve bilimsel asistanlar.',
  ],
  ['Web Araştırma', 'web-arastirma', 'FolderSearch', 'sky', 'Web tarama ve kaynak derleme AI.’ı.'],
  ['Belge Soru-Cevap', 'belge-soru-cevap', 'FileSearch', 'blue', 'PDF/doküman üzerinde Q&A.'],
  ['Bilgi Bankası', 'bilgi-bankasi', 'Library', 'indigo', 'Kurumsal wiki ve knowledge base AI.’ı.'],

  // Eğitim & yaşam
  ['Eğitim', 'egitim', 'GraduationCap', 'indigo', 'Öğrenme, özet ve eğitim asistanları.'],
  ['Dil Öğrenme', 'dil-ogrenme', 'Languages', 'sky', 'Yabancı dil pratiği ve ders planı.'],
  ['Sınav Hazırlık', 'sinav-hazirlik', 'School', 'violet', 'Soru bankası ve sınav simülasyonu.'],
  ['Çocuk & Ebeveyn', 'cocuk-ebeveyn', 'Baby', 'pink', 'Çocuk eğitimi ve ebeveynlik asistanları.'],
  [
    'Sağlık & Yaşam',
    'saglik-yasam',
    'Stethoscope',
    'rose',
    'Medikal karar desteği ve sağlık AI.’ı.',
  ],
  ['Sağlıklı Yaşam', 'saglikli-yasam', 'HeartPulse', 'rose', 'Fitness, beslenme ve wellness.'],
  ['Fitness', 'fitness', 'Dumbbell', 'lime', 'Antrenman planı ve form takibi.'],
  ['Beslenme', 'beslenme', 'Utensils', 'green', 'Diyet, tarif ve besin analizi.'],
  ['Mental Sağlık', 'mental-saglik', 'Smile', 'teal', 'Mindfulness ve mental wellness araçları.'],
  [
    'Erişilebilirlik',
    'erisilebilirlik',
    'Accessibility',
    'blue',
    'Erişilebilirlik denetimi ve uyum araçları.',
  ],
  ['Hayırseverlik', 'hayirseverlik', 'HandHeart', 'rose', 'Bağış ve sivil toplum AI araçları.'],

  // Sektörler
  [
    'Emlak & İnşaat',
    'emlak-insaat',
    'Building2',
    'stone',
    'Emlak listesi ve görselleştirme AI.’ı.',
  ],
  ['İç Mimarlık', 'ic-mimarlik', 'Home', 'amber', 'İç mekân tasarımı ve staging AI.’ı.'],
  ['Harita & Konum', 'harita-konum', 'MapPin', 'teal', 'Konum zekâsı ve coğrafi analiz.'],
  ['Seyahat', 'seyahat', 'Plane', 'sky', 'Seyahat planlama ve rota asistanları.'],
  [
    'Otel & Konaklama',
    'otel-konaklama',
    'Hotel',
    'cyan',
    'Konaklama operasyon ve misafir deneyimi.',
  ],
  ['Otomotiv', 'otomotiv', 'Car', 'slate', 'Otomotiv tasarım ve servis AI.’ı.'],
  ['Lojistik', 'lojistik', 'Ship', 'blue', 'Rota, filo ve lojistik optimizasyonu.'],
  ['Tarım', 'tarim', 'Leaf', 'lime', 'Tarım zekâsı ve verim analizi.'],
  ['İklim & Enerji', 'iklim-enerji', 'Sun', 'amber', 'Enerji, sürdürülebilirlik ve iklim AI.’ı.'],
  ['Çevre', 'cevre', 'Recycle', 'green', 'Çevre izleme ve sürdürülebilirlik araçları.'],
  ['Moda', 'moda', 'Shirt', 'fuchsia', 'Moda tasarımı ve stil asistanları.'],
  ['Güzellik', 'guzellik', 'Flower2', 'pink', 'Güzellik, makyaj ve bakım AI.’ı.'],
  ['Yemek & Mutfak', 'yemek-mutfak', 'Coffee', 'orange', 'Tarif, menü ve mutfak asistanları.'],
  ['Şarap & İçecek', 'sarap-icecek', 'Wine', 'rose', 'İçecek eşleştirme ve tadım notları.'],
  ['Evcil Hayvan', 'evcil-hayvan', 'PawPrint', 'amber', 'Pet bakım ve eğitim asistanları.'],
  ['Spor', 'spor', 'Trophy', 'lime', 'Spor analizi ve performans AI.’ı.'],
  ['Hukuk Bürosu', 'hukuk-burosu', 'Scale', 'stone', 'Hukuk ofisi otomasyon araçları.'],
  ['Sigorta', 'sigorta', 'Shield', 'blue', 'Hasar, risk ve sigorta süreç AI.’ı.'],
  ['Bankacılık', 'bankacilik', 'Landmark', 'emerald', 'Bankacılık ürün ve risk asistanları.'],
  ['Kripto & Web3', 'kripto-web3', 'Orbit', 'violet', 'Kripto analiz ve Web3 araçları.'],
  ['Bilim & Lab', 'bilim-lab', 'FlaskConical', 'cyan', 'Laboratuvar ve bilimsel keşif AI.’ı.'],
  ['Kimya & Malzeme', 'kimya-malzeme', 'Atom', 'indigo', 'Molekül ve malzeme keşfi.'],
  ['Uzay', 'uzay', 'Orbit', 'slate', 'Uzay verisi ve simülasyon AI.’ı.'],
  ['Savunma', 'savunma', 'Swords', 'red', 'Savunma ve simülasyon odaklı AI (etik kullanım).'],

  // Eğlence
  [
    'Oyun & Eğlence',
    'oyun-eglence',
    'Gamepad2',
    'violet',
    'Oyun varlığı, NPC ve interaktif eğlence.',
  ],
  ['Oyun Hikâyesi', 'oyun-hikayesi', 'Drama', 'purple', 'Oyun anlatısı ve quest üretimi.'],
  ['Oyun Asset', 'oyun-asset', 'Joystick', 'fuchsia', '2D/3D oyun asset üretimi.'],
  ['Film & Dizi', 'film-dizi', 'Popcorn', 'red', 'Film/dizi keşif ve senaryo araçları.'],
  ['Yayıncılık', 'yayincilik', 'Tv', 'indigo', 'Canlı yayın ve içerik planlama.'],
  ['Streaming', 'streaming', 'MonitorPlay', 'sky', 'Streaming içerik ve klip üretimi.'],

  // Diğer
  ['QR & Barkod', 'qr-barkod', 'QrCode', 'slate', 'QR, barkod ve etiket üretimi.'],
  ['Paylaşım & Viral', 'paylasim-viral', 'Hash', 'pink', 'Viral içerik ve trend analizi.'],
  [
    'Topluluk Yönetimi',
    'topluluk-yonetimi',
    'Users',
    'violet',
    'Discord/forum topluluk asistanları.',
  ],
  ['İçerik Takvimi', 'icerik-takvimi', 'Calendar', 'orange', 'İçerik planlama ve yayın takvimi.'],
  ['A/B Test', 'ab-test', 'ChartSpline', 'teal', 'Deney tasarımı ve varyant analizi.'],
  [
    'Analitik Dashboard',
    'analitik-dashboard',
    'BarChart3',
    'blue',
    'Metrik dashboard ve insight AI.’ı.',
  ],
  ['İş Zekâsı', 'is-zekasi', 'PieChart', 'indigo', 'BI, raporlama ve karar desteği.'],
  ['Tahminleme', 'tahminleme', 'Activity', 'emerald', 'Talep, churn ve tahmin modelleri.'],
  ['Kişiselleştirme', 'kisisellestirme', 'Puzzle', 'fuchsia', 'Öneri motoru ve kişiselleştirme.'],
  ['Arama Deneyimi', 'arama-deneyimi', 'Compass', 'cyan', 'Site içi arama ve discovery UX.'],
  [
    'Müşteri Yolculuğu',
    'musteri-yolculugu',
    'MapPin',
    'sky',
    'Journey map ve deneyim optimizasyonu.',
  ],
  ['İnovasyon', 'inovasyon', 'Lightbulb', 'yellow', 'Fikir üretimi ve inovasyon atölyeleri.'],
  ['Diğer', 'diger', 'Layers', 'slate', 'Diğer kategorilere sığmayan yenilikçi AI araçları.'],
];

function buildFromDefs(defs) {
  const config = {};
  const seed = [];

  for (const [name, slug, iconKey, colorKey, description] of defs) {
    const colorTheme = COLORS[colorKey] || COLORS.slate;
    const icon = ICONS[iconKey] || LayoutTemplate;
    config[slug] = {
      icon,
      ...colorTheme,
      description,
    };
    seed.push({ name, slug });
  }

  return { config, seed };
}

const built = buildFromDefs(CATEGORY_DEFS);

export const categoryConfig = built.config;
export const CATEGORY_SEED = built.seed;
export const CATEGORY_ORDER = new Map(
  CATEGORY_SEED.map((category, index) => [category.slug, index])
);

export const defaultCategoryConfig = {
  icon: LayoutTemplate,
  color: 'primary',
  gradient: 'from-primary/20 to-primary/10',
  border: 'border-primary/30',
  text: 'text-primary',
  description: 'Bu kategori altındaki en yenilikçi ve popüler yapay zeka araçlarını keşfedin.',
};

export function getCategoryConfig(slug) {
  return categoryConfig[slug] || defaultCategoryConfig;
}

export function getCategoryCount() {
  return CATEGORY_SEED.length;
}

function normalizeCategoryValue(value) {
  return normalizeCategoryLookupKey(value);
}

export function sortCategoriesByCanonicalOrder(categories = []) {
  return [...categories].sort((a, b) => {
    const aOrder = CATEGORY_ORDER.has(a.slug)
      ? CATEGORY_ORDER.get(a.slug)
      : Number.MAX_SAFE_INTEGER;
    const bOrder = CATEGORY_ORDER.has(b.slug)
      ? CATEGORY_ORDER.get(b.slug)
      : Number.MAX_SAFE_INTEGER;

    if (aOrder !== bOrder) return aOrder - bOrder;

    return normalizeCategoryValue(a.name).localeCompare(normalizeCategoryValue(b.name), 'tr');
  });
}
