import {
  Image as ImageIcon,
  Code2,
  Megaphone,
  PenTool,
  Music,
  Zap,
  Palette,
  GraduationCap,
  Box,
  Search,
  MessageSquare,
  Briefcase,
  Bot,
  Video,
  Database,
  LayoutTemplate,
  Shield,
  HeartPulse,
  Scale,
  ShoppingCart,
  Gamepad2,
  Mic2,
  Film,
  Sparkles,
  LineChart,
  Workflow,
  Cpu,
  Globe2,
  Users,
  BookOpen,
  Camera,
  Headphones,
  Building2,
  Stethoscope,
  Landmark,
  Languages,
  Binary,
  Rocket,
  Layers,
  Wrench,
  Brain,
} from 'lucide-react';

/**
 * Kategori vitrini: ikon, renk teması ve SEO açıklamaları.
 * DB slug ile eşleşir; bilinmeyen slug → defaultCategoryConfig.
 */
export const categoryConfig = {
  // --- Temel / mevcut ---
  'gorsel-video': {
    icon: Video,
    color: 'purple',
    gradient: 'from-purple-500/20 to-fuchsia-500/20',
    border: 'border-purple-500/30',
    text: 'text-purple-500',
    description:
      'Görsel üretimi, video düzenleme ve tasarım için en yenilikçi yapay zeka araçları.',
  },
  'kod-yazilim': {
    icon: Code2,
    color: 'blue',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
    description: 'Yazılımcılar için kod asistanları, hata ayıklama ve mimari AI araçları.',
  },
  pazarlama: {
    icon: Megaphone,
    color: 'orange',
    gradient: 'from-orange-500/20 to-amber-500/20',
    border: 'border-orange-500/30',
    text: 'text-orange-500',
    description: 'SEO, içerik stratejisi ve pazarlama kampanyaları için yapay zeka çözümleri.',
  },
  'metin-yazarligi': {
    icon: PenTool,
    color: 'green',
    gradient: 'from-green-500/20 to-emerald-500/20',
    border: 'border-green-500/30',
    text: 'text-green-500',
    description:
      'Blog yazıları, makaleler ve yaratıcı metinler üretmek için gelişmiş dil modelleri.',
  },
  'ses-muzik': {
    icon: Music,
    color: 'rose',
    gradient: 'from-rose-500/20 to-pink-500/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
    description: 'Seslendirme, müzik üretimi ve ses düzenleme için AI tabanlı stüdyo araçları.',
  },
  uretkenlik: {
    icon: Zap,
    color: 'yellow',
    gradient: 'from-yellow-500/20 to-amber-400/20',
    border: 'border-yellow-500/30',
    text: 'text-yellow-500',
    description: 'Günlük iş akışınızı hızlandıracak ve verimliliğinizi artıracak asistanlar.',
  },
  tasarim: {
    icon: Palette,
    color: 'pink',
    gradient: 'from-pink-500/20 to-rose-400/20',
    border: 'border-pink-500/30',
    text: 'text-pink-500',
    description: 'UI/UX, illüstrasyon ve grafik tasarım süreçlerinizi otomatikleştiren araçlar.',
  },
  egitim: {
    icon: GraduationCap,
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-blue-500/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
    description:
      'Öğrenme sürecinizi hızlandıran, özet çıkaran ve araştırma yapan eğitim asistanları.',
  },
  '3d-modelleme': {
    icon: Box,
    color: 'teal',
    gradient: 'from-teal-500/20 to-emerald-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
    description: 'Metinden veya görselden 3 boyutlu modeller ve ortamlar üreten AI motorları.',
  },
  'arama-motoru': {
    icon: Search,
    color: 'cyan',
    gradient: 'from-cyan-500/20 to-blue-400/20',
    border: 'border-cyan-500/30',
    text: 'text-cyan-500',
    description:
      'Geleneksel aramayı yapay zeka destekli diyalog ve analiz yeteneğiyle birleştiren motorlar.',
  },
  chatbotlar: {
    icon: MessageSquare,
    color: 'violet',
    gradient: 'from-violet-500/20 to-purple-500/20',
    border: 'border-violet-500/30',
    text: 'text-violet-500',
    description: 'Kullanıcılarla doğal dilde iletişim kurabilen sohbet robotları ve asistanlar.',
  },
  'is-dunyasi': {
    icon: Briefcase,
    color: 'slate',
    gradient: 'from-slate-500/20 to-gray-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
    description: 'Şirket yönetimi, finans ve iş planlaması için profesyonel yapay zeka araçları.',
  },

  // --- Genişletilmiş set ---
  'gorsel-uretim': {
    icon: ImageIcon,
    color: 'fuchsia',
    gradient: 'from-fuchsia-500/20 to-purple-400/20',
    border: 'border-fuchsia-500/30',
    text: 'text-fuchsia-500',
    description: 'Metinden görsel, stil transferi ve yaratıcı illüstrasyon üreten AI modelleri.',
  },
  'video-uretim': {
    icon: Film,
    color: 'red',
    gradient: 'from-red-500/20 to-orange-400/20',
    border: 'border-red-500/30',
    text: 'text-red-500',
    description: 'Kısa/uzun video üretimi, animasyon ve sinematik AI video araçları.',
  },
  'ses-klonlama': {
    icon: Mic2,
    color: 'rose',
    gradient: 'from-rose-500/20 to-red-400/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
    description: 'Ses klonlama, dublaj ve gerçekçi konuşma sentezi araçları.',
  },
  'podcast-yayin': {
    icon: Headphones,
    color: 'amber',
    gradient: 'from-amber-500/20 to-yellow-400/20',
    border: 'border-amber-500/30',
    text: 'text-amber-500',
    description: 'Podcast düzenleme, özetleme ve yayın otomasyonu için AI araçları.',
  },
  'ceviri-dil': {
    icon: Languages,
    color: 'sky',
    gradient: 'from-sky-500/20 to-blue-400/20',
    border: 'border-sky-500/30',
    text: 'text-sky-500',
    description: 'Çeviri, yerelleştirme ve çok dilli içerik üretimi çözümleri.',
  },
  'veri-analiz': {
    icon: LineChart,
    color: 'emerald',
    gradient: 'from-emerald-500/20 to-teal-400/20',
    border: 'border-emerald-500/30',
    text: 'text-emerald-500',
    description: 'Veri analizi, dashboard ve iş zekâsı için yapay zeka destekli araçlar.',
  },
  'otomasyon-ajan': {
    icon: Workflow,
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-violet-400/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
    description: 'Otonom ajanlar, RPA ve iş akışı otomasyonu platformları.',
  },
  'musteri-destek': {
    icon: Headphones,
    color: 'blue',
    gradient: 'from-blue-500/20 to-cyan-400/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
    description: 'Destek botları, ticket sınıflandırma ve müşteri deneyimi AI araçları.',
  },
  'satis-crm': {
    icon: ShoppingCart,
    color: 'orange',
    gradient: 'from-orange-500/20 to-red-400/20',
    border: 'border-orange-500/30',
    text: 'text-orange-500',
    description: 'Satış tahminleme, lead skorlama ve CRM otomasyonu için AI.',
  },
  'insan-kaynaklari': {
    icon: Users,
    color: 'teal',
    gradient: 'from-teal-500/20 to-cyan-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
    description: 'İşe alım, CV tarama ve çalışan deneyimi için yapay zeka araçları.',
  },
  'hukuk-uyumluluk': {
    icon: Scale,
    color: 'slate',
    gradient: 'from-slate-500/20 to-zinc-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
    description: 'Sözleşme inceleme, yasal araştırma ve uyumluluk asistanları.',
  },
  'saglik-yasam': {
    icon: Stethoscope,
    color: 'rose',
    gradient: 'from-rose-500/20 to-pink-400/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
    description: 'Sağlık, wellness ve medikal karar desteği odaklı AI uygulamaları.',
  },
  'finans-yatirim': {
    icon: Landmark,
    color: 'green',
    gradient: 'from-green-500/20 to-lime-400/20',
    border: 'border-green-500/30',
    text: 'text-green-500',
    description: 'Finansal analiz, bütçe ve yatırım karar desteği araçları.',
  },
  'guvenlik-siber': {
    icon: Shield,
    color: 'red',
    gradient: 'from-red-500/20 to-rose-400/20',
    border: 'border-red-500/30',
    text: 'text-red-500',
    description: 'Tehdit tespiti, güvenlik analizi ve siber savunma AI araçları.',
  },
  'oyun-eglence': {
    icon: Gamepad2,
    color: 'violet',
    gradient: 'from-violet-500/20 to-fuchsia-400/20',
    border: 'border-violet-500/30',
    text: 'text-violet-500',
    description: 'Oyun varlığı üretimi, NPC diyalogu ve interaktif eğlence AI’ları.',
  },
  'sosyal-medya': {
    icon: Globe2,
    color: 'sky',
    gradient: 'from-sky-500/20 to-indigo-400/20',
    border: 'border-sky-500/30',
    text: 'text-sky-500',
    description: 'İçerik planlama, caption ve sosyal medya büyüme araçları.',
  },
  'arastirma-akademik': {
    icon: BookOpen,
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-blue-400/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
    description: 'Akademik arama, makale özeti ve bilimsel araştırma asistanları.',
  },
  'urun-yonetimi': {
    icon: Layers,
    color: 'cyan',
    gradient: 'from-cyan-500/20 to-teal-400/20',
    border: 'border-cyan-500/30',
    text: 'text-cyan-500',
    description: 'Ürün keşfi, kullanıcı araştırması ve roadmap için AI araçları.',
  },
  'no-code-low-code': {
    icon: LayoutTemplate,
    color: 'amber',
    gradient: 'from-amber-500/20 to-orange-400/20',
    border: 'border-amber-500/30',
    text: 'text-amber-500',
    description: 'Kod yazmadan uygulama ve otomasyon kurmanızı sağlayan AI platformları.',
  },
  'mlops-model': {
    icon: Cpu,
    color: 'slate',
    gradient: 'from-slate-500/20 to-blue-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
    description: 'Model eğitimi, dağıtım ve MLOps altyapısı araçları.',
  },
  'veritabani-bilgi': {
    icon: Database,
    color: 'blue',
    gradient: 'from-blue-500/20 to-indigo-400/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
    description: 'Vektör DB, RAG ve bilgi tabanı yönetim çözümleri.',
  },
  'prompt-muhendisligi': {
    icon: Binary,
    color: 'purple',
    gradient: 'from-purple-500/20 to-violet-400/20',
    border: 'border-purple-500/30',
    text: 'text-purple-500',
    description: 'Prompt kütüphaneleri, değerlendirme ve optimizasyon araçları.',
  },
  'kisisel-asistan': {
    icon: Bot,
    color: 'cyan',
    gradient: 'from-cyan-500/20 to-sky-400/20',
    border: 'border-cyan-500/30',
    text: 'text-cyan-500',
    description: 'Günlük planlama, e-posta ve kişisel verimlilik asistanları.',
  },
  'toplanti-not': {
    icon: Mic2,
    color: 'teal',
    gradient: 'from-teal-500/20 to-emerald-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
    description: 'Toplantı kaydı, deşifre ve aksiyon maddesi çıkaran AI araçları.',
  },
  'fotograf-duzenleme': {
    icon: Camera,
    color: 'pink',
    gradient: 'from-pink-500/20 to-rose-400/20',
    border: 'border-pink-500/30',
    text: 'text-pink-500',
    description: 'Fotoğraf iyileştirme, arka plan kaldırma ve retuş AI araçları.',
  },
  'sunum-dokuman': {
    icon: BookOpen,
    color: 'orange',
    gradient: 'from-orange-500/20 to-amber-400/20',
    border: 'border-orange-500/30',
    text: 'text-orange-500',
    description: 'Sunum, teklif ve doküman üretimi için yapay zeka yardımcıları.',
  },
  'emlak-insaat': {
    icon: Building2,
    color: 'stone',
    gradient: 'from-stone-500/20 to-amber-400/20',
    border: 'border-stone-500/30',
    text: 'text-stone-500',
    description: 'Emlak listeleri, görselleştirme ve inşaat planlama AI araçları.',
  },
  'saglikli-yasam': {
    icon: HeartPulse,
    color: 'rose',
    gradient: 'from-rose-500/20 to-red-400/20',
    border: 'border-rose-500/30',
    text: 'text-rose-500',
    description: 'Fitness, beslenme ve mental wellness odaklı AI uygulamaları.',
  },
  girisimcilik: {
    icon: Rocket,
    color: 'violet',
    gradient: 'from-violet-500/20 to-indigo-400/20',
    border: 'border-violet-500/30',
    text: 'text-violet-500',
    description: 'İş fikri, pitch deck ve büyüme stratejisi için AI araçları.',
  },
  'gelistirici-araclari': {
    icon: Wrench,
    color: 'blue',
    gradient: 'from-blue-500/20 to-slate-400/20',
    border: 'border-blue-500/30',
    text: 'text-blue-500',
    description: 'API test, dokümantasyon ve geliştirici üretkenlik araçları.',
  },
  'bilgi-yonetimi': {
    icon: Brain,
    color: 'indigo',
    gradient: 'from-indigo-500/20 to-purple-400/20',
    border: 'border-indigo-500/30',
    text: 'text-indigo-500',
    description: 'Not alma, second brain ve kişisel bilgi yönetimi AI’ları.',
  },
  'e-ticaret': {
    icon: ShoppingCart,
    color: 'emerald',
    gradient: 'from-emerald-500/20 to-green-400/20',
    border: 'border-emerald-500/30',
    text: 'text-emerald-500',
    description: 'Ürün açıklaması, fiyatlandırma ve e-ticaret optimizasyonu araçları.',
  },
  'icerik-moderasyon': {
    icon: Shield,
    color: 'slate',
    gradient: 'from-slate-500/20 to-red-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
    description: 'İçerik filtreleme, toksisite ve güvenlik moderasyon araçları.',
  },
  'avatar-dijital-insan': {
    icon: Sparkles,
    color: 'fuchsia',
    gradient: 'from-fuchsia-500/20 to-pink-400/20',
    border: 'border-fuchsia-500/30',
    text: 'text-fuchsia-500',
    description: 'Dijital avatar, talking head ve sanal sunucu üretimi araçları.',
  },
  'harita-konum': {
    icon: Globe2,
    color: 'teal',
    gradient: 'from-teal-500/20 to-cyan-400/20',
    border: 'border-teal-500/30',
    text: 'text-teal-500',
    description: 'Konum zekâsı, harita analizi ve coğrafi AI çözümleri.',
  },
  diger: {
    icon: Layers,
    color: 'slate',
    gradient: 'from-slate-500/20 to-zinc-400/20',
    border: 'border-slate-500/30',
    text: 'text-slate-500',
    description: 'Diğer kategorilere sığmayan yenilikçi yapay zeka araçları.',
  },
};

export const defaultCategoryConfig = {
  icon: LayoutTemplate,
  color: 'primary',
  gradient: 'from-primary/20 to-primary/10',
  border: 'border-primary/30',
  text: 'text-primary',
  description: 'Bu kategori altındaki en yenilikçi ve popüler yapay zeka araçlarını keşfedin.',
};

/** Seed / UI için kanonik kategori listesi (name + slug) */
export const CATEGORY_SEED = [
  { name: 'Görsel & Video', slug: 'gorsel-video' },
  { name: 'Görsel Üretim', slug: 'gorsel-uretim' },
  { name: 'Video Üretim', slug: 'video-uretim' },
  { name: 'Fotoğraf Düzenleme', slug: 'fotograf-duzenleme' },
  { name: '3D Modelleme', slug: '3d-modelleme' },
  { name: 'Avatar & Dijital İnsan', slug: 'avatar-dijital-insan' },
  { name: 'Ses & Müzik', slug: 'ses-muzik' },
  { name: 'Ses Klonlama', slug: 'ses-klonlama' },
  { name: 'Podcast & Yayın', slug: 'podcast-yayin' },
  { name: 'Metin Yazarlığı', slug: 'metin-yazarligi' },
  { name: 'Çeviri & Dil', slug: 'ceviri-dil' },
  { name: 'Sunum & Doküman', slug: 'sunum-dokuman' },
  { name: 'Kod & Yazılım', slug: 'kod-yazilim' },
  { name: 'Geliştirici Araçları', slug: 'gelistirici-araclari' },
  { name: 'No-Code / Low-Code', slug: 'no-code-low-code' },
  { name: 'MLOps & Model', slug: 'mlops-model' },
  { name: 'Veritabanı & Bilgi', slug: 'veritabani-bilgi' },
  { name: 'Prompt Mühendisliği', slug: 'prompt-muhendisligi' },
  { name: 'Chatbotlar', slug: 'chatbotlar' },
  { name: 'Kişisel Asistan', slug: 'kisisel-asistan' },
  { name: 'Otomasyon & Ajan', slug: 'otomasyon-ajan' },
  { name: 'Toplantı & Not', slug: 'toplanti-not' },
  { name: 'Üretkenlik', slug: 'uretkenlik' },
  { name: 'Bilgi Yönetimi', slug: 'bilgi-yonetimi' },
  { name: 'Pazarlama', slug: 'pazarlama' },
  { name: 'Sosyal Medya', slug: 'sosyal-medya' },
  { name: 'Satış & CRM', slug: 'satis-crm' },
  { name: 'E-Ticaret', slug: 'e-ticaret' },
  { name: 'Müşteri Destek', slug: 'musteri-destek' },
  { name: 'İnsan Kaynakları', slug: 'insan-kaynaklari' },
  { name: 'İş Dünyası', slug: 'is-dunyasi' },
  { name: 'Finans & Yatırım', slug: 'finans-yatirim' },
  { name: 'Hukuk & Uyumluluk', slug: 'hukuk-uyumluluk' },
  { name: 'Güvenlik & Siber', slug: 'guvenlik-siber' },
  { name: 'İçerik Moderasyon', slug: 'icerik-moderasyon' },
  { name: 'Eğitim', slug: 'egitim' },
  { name: 'Araştırma & Akademik', slug: 'arastirma-akademik' },
  { name: 'Arama Motoru', slug: 'arama-motoru' },
  { name: 'Veri Analiz', slug: 'veri-analiz' },
  { name: 'Tasarım', slug: 'tasarim' },
  { name: 'Ürün Yönetimi', slug: 'urun-yonetimi' },
  { name: 'Girişimcilik', slug: 'girisimcilik' },
  { name: 'Oyun & Eğlence', slug: 'oyun-eglence' },
  { name: 'Sağlık & Yaşam', slug: 'saglik-yasam' },
  { name: 'Sağlıklı Yaşam', slug: 'saglikli-yasam' },
  { name: 'Emlak & İnşaat', slug: 'emlak-insaat' },
  { name: 'Harita & Konum', slug: 'harita-konum' },
  { name: 'Diğer', slug: 'diger' },
];

export function getCategoryConfig(slug) {
  return categoryConfig[slug] || defaultCategoryConfig;
}
