export const KASIF_CONCEPTS = {
  'gorsel-uretim': ['görsel', 'resim', 'fotoğraf', 'illüstrasyon', 'image'],
  'video-uretim': ['video', 'animasyon', 'montaj', 'film'],
  'ses-uretim': ['ses', 'seslendirme', 'dublaj', 'podcast', 'voice', 'audio', 'tts'],
  'muzik-uretim': ['müzik', 'şarkı', 'beste', 'melodi', 'music', 'song'],
  'metin-yazarligi': [
    'metin',
    'yazı',
    'blog',
    'içerik',
    'makale',
    'çeviri',
    'çevir',
    'tercüme',
    'translation',
    'diller arası',
  ],
  'kod-yazilim': ['kod', 'yazılım', 'programlama', 'developer', 'coding', 'software', 'test'],
  pazarlama: ['pazarlama', 'marketing', 'seo', 'reklam', 'advertising', 'sosyal medya'],
  'veri-analiz': ['veri', 'data', 'analiz', 'analysis', 'rapor', 'report', 'sql', 'istatistik'],
  'otomasyon-ajan': ['otomasyon', 'ajan', 'agent', 'workflow', 'iş akışı'],
  chatbotlar: ['sohbet', 'chatbot', 'asistan', 'chat'],
  uretkenlik: [
    'sunum',
    'presentation',
    'slayt',
    'slide',
    'not',
    'notes',
    'toplantı',
    'meeting',
    'takvim',
    'görev',
  ],
};

export const FREE_WORDS = ['ücretsiz', 'free', 'bedava', 'açık kaynak', 'open-source'];
export const PAID_WORDS = ['ücretli', 'premium', 'paid', 'enterprise'];

export const KASIF_GOALS = {
  'meeting-notes': {
    queryGroups: [
      ['toplantı', 'meeting'],
      ['not', 'notes', 'özet', 'summary', 'transkript', 'transcript', 'kaydet'],
    ],
    evidence: ['transkript', 'özet', 'toplantı notu', 'kayıt', 'deşifre'],
  },
  'coding-assistant': {
    queryGroups: [
      ['kod', 'yazılım', 'programlama', 'code', 'coding', 'software'],
      ['yaz', 'geliştir', 'asistan', 'tamamla', 'write', 'build', 'assistant', 'complete'],
    ],
    evidence: ['kod yaz', 'kod üret', 'kod tamamlama', 'programlama', 'geliştirici asistan'],
    negativeEvidence: ['arasında kod dönüşümü', 'programlama dillerini öğreten', 'eğitim deneyimi'],
  },
  'image-generation': {
    queryGroups: [
      ['görsel', 'resim', 'fotoğraf', 'illüstrasyon', 'image', 'picture', 'photo', 'illustration'],
      ['üret', 'oluştur', 'çiz', 'yap', 'generate', 'create', 'draw', 'make'],
    ],
    evidence: [
      'metinden görsel',
      'görsel üret',
      'resim oluştur',
      'image generation',
      'illüstrasyon',
    ],
    negativeEvidence: ['çözünürlüğünü artır', 'parazit temizler', 'görsel büyüt'],
  },
  'video-generation': {
    queryGroups: [
      ['video', 'animasyon', 'animation', 'film'],
      ['üret', 'oluştur', 'yap', 'dönüştür', 'generate', 'create', 'make', 'convert'],
    ],
    evidence: [
      'metinden video',
      'video üret',
      'video oluştur',
      'text to video',
      'animasyon oluştur',
    ],
    negativeEvidence: [
      'çözünürlüğünü artır',
      'çözünürlüklü videoları',
      'video iyileştir',
      'gürültü azalt',
      'yükselten',
    ],
  },
  'voice-generation': {
    queryGroups: [
      ['ses', 'seslendirme', 'dublaj', 'voice', 'audio', 'speech'],
      ['üret', 'oluştur', 'yap', 'dönüştür', 'klonla', 'generate', 'create', 'convert', 'clone'],
    ],
    evidence: [
      'metinden sese',
      'metni sese',
      'text to speech',
      'seslendirme',
      'ses klonlama',
      'voice cloning',
      'dublaj',
    ],
    negativeEvidence: ['gürültü azalt', 'transkript', 'toplantı özeti', 'ses temizleme'],
  },
  'music-generation': {
    queryGroups: [
      ['müzik', 'şarkı', 'beste', 'melodi', 'music', 'song', 'melody'],
      ['üret', 'oluştur', 'yap', 'bestele', 'generate', 'create', 'compose', 'make'],
    ],
    evidence: [
      'müzik üret',
      'şarkı oluştur',
      'music generation',
      'beste',
      'melodi',
      'vokal müzik',
      'enstrümantal müzik',
    ],
    negativeEvidence: ['transkript', 'podcast düzenleme', 'gürültü azalt', 'ses temizleme'],
  },
  'workflow-automation': {
    queryGroups: [
      ['otomasyon', 'automation', 'workflow', 'iş akışı', 'ajan', 'agent'],
      [
        'otomatikleştir',
        'automate',
        'bağla',
        'connect',
        'tekrarlayan',
        'repetitive',
        'entegrasyon',
        'integration',
        'görev',
      ],
    ],
    evidence: [
      'iş akışı otomasyonu',
      'workflow automation',
      'tekrarlayan görev',
      'iş akışları',
      'uygulamaları birbirine bağ',
      'entegrasyon',
      'otomatikleştir',
      'no-code otomasyon',
    ],
    negativeEvidence: ['görsel oluştur', 'video çözünürlük', 'fotoğraf üret', 'görüntü kalitesi'],
  },
  'data-analysis': {
    queryGroups: [
      ['veri', 'data', 'csv', 'excel', 'sql', 'dataset'],
      [
        'analiz',
        'analysis',
        'analyze',
        'rapor',
        'report',
        'grafik',
        'chart',
        'visualize',
        'görselleştir',
        'dashboard',
      ],
    ],
    evidence: [
      'veri analizi',
      'data analysis',
      'csv',
      'veri set',
      'elektronik tablo',
      'veri görselleştirme',
      'dashboard',
      'grafik oluştur',
      'grafik çiz',
      'istatistiksel model',
      'iş zekası',
    ],
    negativeEvidence: [
      'seo analizi',
      'içerik optimizasyon',
      'görsel üret',
      'fotoğraf oluştur',
      'reklam materyalleri',
      'proje yönetimi',
      'zaman takip',
    ],
  },
  'content-writing': {
    queryGroups: [
      ['blog', 'makale', 'article', 'içerik', 'content', 'metin', 'copy'],
      ['yaz', 'write', 'hazırla', 'create', 'kaleme'],
    ],
    evidence: [
      'blog yazısı',
      'makale',
      'içerik üret',
      'metin üret',
      'seo uyumlu metin',
      'reklam metni',
      'pazarlama metni',
    ],
    negativeEvidence: ['görsel üret', 'video oluştur', 'kod üret', 'seslendirme'],
  },
  translation: {
    queryGroups: [
      ['çeviri', 'çevir', 'tercüme', 'translation', 'translate'],
      ['metin', 'text', 'dil', 'language', 'türkçe', 'turkish', 'ingilizce', 'english'],
    ],
    evidence: [
      'metin çeviri',
      'diller arası çeviri',
      'çok dilli çeviri',
      'çeviri yap',
      'translation',
      'tercüme',
    ],
    negativeEvidence: [
      'kod çeviri',
      'kod anlama',
      'programlama',
      'toplantı özeti',
      'toplantı platform',
      'seslendirme',
      'ses klonlama',
      'video oluştur',
      'videoya dönüştür',
    ],
  },
  'presentation-creation': {
    queryGroups: [
      ['sunum', 'presentation', 'slayt', 'slide', 'deck'],
      [
        'hazırla',
        'oluştur',
        'üret',
        'yap',
        'öner',
        'araç',
        'gerekli',
        'create',
        'generate',
        'make',
        'recommend',
        'tool',
      ],
    ],
    evidence: ['sunum oluştur', 'sunum hazırla', 'slayt oluştur', 'presentation', 'sunum', 'slayt'],
  },
};
