/**
 * Kâşif kavram ve görev sözlüğü.
 * Kavramlar sorgu konusunu (topic) tanır; hedefler (goals) belirli işleri puanlar.
 * Platform PRIMARY_CATEGORIES ile hizalı tutulur.
 */

export const KASIF_CONCEPTS = {
  'gorsel-uretim': [
    'görsel',
    'resim',
    'fotoğraf',
    'illüstrasyon',
    'image',
    'picture',
    'photo',
    'illustration',
    'drawing',
  ],
  'video-uretim': ['video', 'animasyon', 'montaj', 'film', 'animation', 'clip', 'motion'],
  'ses-uretim': [
    'ses',
    'seslendirme',
    'dublaj',
    'podcast',
    'voice',
    'audio',
    'tts',
    'speech',
    'narration',
  ],
  'muzik-uretim': ['müzik', 'şarkı', 'beste', 'melodi', 'music', 'song', 'melody', 'beat'],
  '3d-modelleme': ['3d', 'üç boyut', 'avatar', 'dijital insan', 'model', 'mesh', 'render'],
  tasarim: [
    'tasarım',
    'design',
    'logo',
    'marka',
    'brand',
    'ui',
    'ux',
    'figma',
    'grafik',
    'graphic',
    'wireframe',
  ],
  'metin-yazarligi': [
    'metin',
    'yazı',
    'blog',
    'içerik',
    'makale',
    'çeviri',
    'çevir',
    'tercüme',
    'translation',
    'diller arası',
    'copy',
    'senaryo',
    'script',
    'e-posta',
    'email',
  ],
  'kod-yazilim': [
    'kod',
    'yazılım',
    'programlama',
    'developer',
    'coding',
    'software',
    'test',
    'debug',
    'ide',
  ],
  'no-code-low-code': [
    'no-code',
    'nocode',
    'low-code',
    'lowcode',
    'kodsuz',
    'form oluştur',
    'landing page',
    'website builder',
    'site kur',
  ],
  pazarlama: [
    'pazarlama',
    'marketing',
    'seo',
    'reklam',
    'advertising',
    'sosyal medya',
    'social media',
    'kampanya',
    'campaign',
    'ads',
  ],
  'veri-analiz': [
    'veri',
    'data',
    'analiz',
    'analysis',
    'rapor',
    'report',
    'sql',
    'istatistik',
    'dashboard',
    'bi',
  ],
  'otomasyon-ajan': [
    'otomasyon',
    'ajan',
    'agent',
    'workflow',
    'iş akışı',
    'automation',
    'zapier',
    'entegrasyon',
  ],
  chatbotlar: ['sohbet', 'chatbot', 'asistan', 'chat', 'llm', 'gpt', 'claude', 'conversational'],
  uretkenlik: [
    'sunum',
    'presentation',
    'slayt',
    'slide',
    'not',
    'notes',
    'toplantı',
    'meeting',
    'takvim',
    'görev',
    'productivity',
    'agenda',
  ],
  'satis-crm': ['satış', 'sales', 'crm', 'lead', 'pipeline', 'müşteri adayı', 'funnel', 'outreach'],
  'e-ticaret': [
    'e-ticaret',
    'eticaret',
    'ecommerce',
    'e-commerce',
    'mağaza',
    'shopify',
    'ürün',
    'product listing',
    'ürün açıklama',
  ],
  'musteri-destek': [
    'destek',
    'support',
    'ticket',
    'müşteri hizmetleri',
    'customer service',
    'helpdesk',
    'canlı sohbet',
    'live chat',
  ],
  'is-dunyasi': [
    'finans',
    'finance',
    'muhasebe',
    'accounting',
    'fatura',
    'invoice',
    'bütçe',
    'budget',
    'iş planı',
  ],
  'insan-kaynaklari': [
    'ik',
    'hr',
    'işe alım',
    'recruiting',
    'cv',
    'özgeçmiş',
    'resume',
    'aday',
    'hiring',
  ],
  'hukuk-uyumluluk': [
    'hukuk',
    'legal',
    'sözleşme',
    'contract',
    'uyumluluk',
    'compliance',
    'gdpr',
    'kvkk',
    'yasal',
  ],
  egitim: [
    'eğitim',
    'education',
    'öğrenme',
    'learning',
    'kurs',
    'course',
    'ders',
    'tutor',
    'öğretmen',
    'study',
  ],
};

export const FREE_WORDS = [
  'ücretsiz',
  'ucretsiz',
  'free',
  'bedava',
  'açık kaynak',
  'acik kaynak',
  'open-source',
  'open source',
  'gratis',
];
export const PAID_WORDS = [
  'ücretli',
  'ucretli',
  'premium',
  'paid',
  'enterprise',
  'abonelikli',
  'subscription',
];

export const KASIF_GOALS = {
  'meeting-notes': {
    queryGroups: [
      ['toplantı', 'meeting'],
      ['not', 'notes', 'özet', 'summary', 'transkript', 'transcript', 'kaydet'],
    ],
    evidence: ['transkript', 'özet', 'toplantı notu', 'kayıt', 'deşifre', 'meeting notes'],
  },
  'coding-assistant': {
    queryGroups: [
      ['kod', 'yazılım', 'programlama', 'code', 'coding', 'software'],
      ['yaz', 'geliştir', 'asistan', 'tamamla', 'write', 'build', 'assistant', 'complete'],
    ],
    evidence: ['kod yaz', 'kod üret', 'kod tamamlama', 'programlama', 'geliştirici asistan', 'ide'],
    negativeEvidence: ['arasında kod dönüşümü', 'programlama dillerini öğreten', 'eğitim deneyimi'],
  },
  'image-generation': {
    queryGroups: [
      ['görsel', 'resim', 'fotoğraf', 'illüstrasyon', 'image', 'picture', 'photo', 'illustration'],
      ['üret', 'oluştur', 'çiz', 'yap', 'generate', 'create', 'draw', 'make'],
    ],
    evidence: [
      'metinden görsel',
      'görsel üret',
      'resim oluştur',
      'image generation',
      'illüstrasyon',
    ],
    negativeEvidence: ['çözünürlüğünü artır', 'parazit temizler', 'görsel büyüt', 'logo tasarım'],
  },
  'video-generation': {
    queryGroups: [
      ['video', 'animasyon', 'animation', 'film'],
      ['üret', 'oluştur', 'yap', 'dönüştür', 'generate', 'create', 'make', 'convert'],
    ],
    evidence: [
      'metinden video',
      'video üret',
      'video oluştur',
      'text to video',
      'animasyon oluştur',
    ],
    negativeEvidence: [
      'çözünürlüğünü artır',
      'çözünürlüklü videoları',
      'video iyileştir',
      'gürültü azalt',
      'yükselten',
    ],
  },
  'voice-generation': {
    queryGroups: [
      ['ses', 'seslendirme', 'dublaj', 'voice', 'audio', 'speech'],
      ['üret', 'oluştur', 'yap', 'dönüştür', 'klonla', 'generate', 'create', 'convert', 'clone'],
    ],
    evidence: [
      'metinden sese',
      'metni sese',
      'text to speech',
      'seslendirme',
      'ses klonlama',
      'voice cloning',
      'dublaj',
    ],
    negativeEvidence: ['gürültü azalt', 'transkript', 'toplantı özeti', 'ses temizleme'],
  },
  'music-generation': {
    queryGroups: [
      ['müzik', 'şarkı', 'beste', 'melodi', 'music', 'song', 'melody'],
      ['üret', 'oluştur', 'yap', 'bestele', 'generate', 'create', 'compose', 'make'],
    ],
    evidence: [
      'müzik üret',
      'şarkı oluştur',
      'music generation',
      'beste',
      'melodi',
      'vokal müzik',
      'enstrümantal müzik',
    ],
    negativeEvidence: ['transkript', 'podcast düzenleme', 'gürültü azalt', 'ses temizleme'],
  },
  'workflow-automation': {
    queryGroups: [
      ['otomasyon', 'automation', 'workflow', 'iş akışı', 'ajan', 'agent'],
      [
        'otomatikleştir',
        'automate',
        'bağla',
        'connect',
        'tekrarlayan',
        'repetitive',
        'entegrasyon',
        'integration',
        'görev',
      ],
    ],
    evidence: [
      'iş akışı otomasyonu',
      'workflow automation',
      'tekrarlayan görev',
      'iş akışları',
      'uygulamaları birbirine bağ',
      'entegrasyon',
      'otomatikleştir',
      'no-code otomasyon',
    ],
    negativeEvidence: ['görsel oluştur', 'video çözünürlük', 'fotoğraf üret', 'görüntü kalitesi'],
  },
  'data-analysis': {
    queryGroups: [
      ['veri', 'data', 'csv', 'excel', 'sql', 'dataset'],
      [
        'analiz',
        'analysis',
        'analyze',
        'rapor',
        'report',
        'grafik',
        'chart',
        'visualize',
        'görselleştir',
        'dashboard',
      ],
    ],
    evidence: [
      'veri analizi',
      'data analysis',
      'csv',
      'veri set',
      'elektronik tablo',
      'veri görselleştirme',
      'dashboard',
      'grafik oluştur',
      'grafik çiz',
      'istatistiksel model',
      'iş zekası',
    ],
    negativeEvidence: [
      'seo analizi',
      'içerik optimizasyon',
      'görsel üret',
      'fotoğraf oluştur',
      'reklam materyalleri',
      'proje yönetimi',
      'zaman takip',
    ],
  },
  'content-writing': {
    queryGroups: [
      ['blog', 'makale', 'article', 'içerik', 'content', 'metin', 'copy'],
      ['yaz', 'write', 'hazırla', 'create', 'kaleme', 'üret', 'generate'],
    ],
    evidence: [
      'blog yazısı',
      'makale',
      'içerik üret',
      'metin üret',
      'seo uyumlu metin',
      'reklam metni',
      'pazarlama metni',
    ],
    negativeEvidence: [
      'görsel üret',
      'video oluştur',
      'kod üret',
      'seslendirme',
      'ürün açıklaması',
      'e-posta kampanya',
    ],
  },
  translation: {
    queryGroups: [
      ['çeviri', 'çevir', 'tercüme', 'translation', 'translate'],
      ['metin', 'text', 'dil', 'language', 'türkçe', 'turkish', 'ingilizce', 'english'],
    ],
    evidence: [
      'metin çeviri',
      'diller arası çeviri',
      'çok dilli çeviri',
      'çeviri yap',
      'translation',
      'tercüme',
    ],
    negativeEvidence: [
      'kod çeviri',
      'kod anlama',
      'programlama',
      'toplantı özeti',
      'toplantı platform',
      'seslendirme',
      'ses klonlama',
      'video oluştur',
      'videoya dönüştür',
    ],
  },
  'presentation-creation': {
    queryGroups: [
      ['sunum', 'presentation', 'slayt', 'slide', 'deck'],
      [
        'hazırla',
        'oluştur',
        'üret',
        'yap',
        'öner',
        'araç',
        'gerekli',
        'create',
        'generate',
        'make',
        'recommend',
        'tool',
      ],
    ],
    evidence: ['sunum oluştur', 'sunum hazırla', 'slayt oluştur', 'presentation', 'sunum', 'slayt'],
  },
  'logo-design': {
    queryGroups: [
      ['logo', 'marka kimliği', 'brand identity', 'branding', 'kurumsal kimlik'],
      ['tasarla', 'oluştur', 'yap', 'üret', 'design', 'create', 'make', 'generate', 'öner'],
    ],
    evidence: [
      'logo tasarım',
      'logo oluştur',
      'marka kimliği',
      'brand identity',
      'logo maker',
      'logo generator',
      'kurumsal kimlik',
    ],
    negativeEvidence: ['metinden görsel', 'fotoğraf üret', 'upscale', 'görsel büyüt'],
  },
  'ui-design': {
    queryGroups: [
      ['ui', 'ux', 'arayüz', 'interface', 'wireframe', 'prototip', 'prototype', 'figma'],
      ['tasarla', 'oluştur', 'design', 'create', 'make', 'araç', 'tool'],
    ],
    evidence: [
      'ui tasarım',
      'ux tasarım',
      'arayüz tasarım',
      'wireframe',
      'prototip',
      'figma',
      'interface design',
      'kullanıcı arayüzü',
    ],
    negativeEvidence: ['logo oluştur', 'fotoğraf üret', 'video oluştur'],
  },
  'chatbot-assistant': {
    queryGroups: [
      [
        'chatbot',
        'sohbet botu',
        'sohbet asistan',
        'chat assistant',
        'llm asistan',
        'yapay zeka asistan',
      ],
      [
        'kur',
        'oluştur',
        'öner',
        'kullan',
        'build',
        'create',
        'recommend',
        'use',
        'soru',
        'cevap',
        'gündelik',
      ],
    ],
    evidence: [
      'sohbet botu',
      'chatbot',
      'yapay zeka asistan',
      'llm',
      'konuşma arayüzü',
      'chat interface',
      'soru cevap',
      'kişisel asistan',
    ],
    negativeEvidence: ['kod asistan', 'ide içinde', 'toplantı özeti', 'seslendirme'],
  },
  'email-writing': {
    queryGroups: [
      ['e-posta', 'email', 'eposta', 'mail'],
      ['yaz', 'write', 'kampanya', 'campaign', 'soğuk', 'cold', 'şablon', 'template', 'hazırla'],
    ],
    evidence: [
      'e-posta yaz',
      'email yaz',
      'e-posta kampanya',
      'cold email',
      'soğuk e-posta',
      'e-posta şablon',
      'newsletter',
      'mail sequence',
    ],
    negativeEvidence: ['müşteri destek', 'ticket', 'canlı sohbet botu'],
  },
  'seo-optimization': {
    queryGroups: [
      ['seo', 'arama motoru', 'search engine'],
      [
        'analiz',
        'analysis',
        'optimize',
        'optimizasyon',
        'sıralama',
        'ranking',
        'anahtar kelime',
        'keyword',
      ],
    ],
    evidence: [
      'seo analiz',
      'seo optimizasyon',
      'anahtar kelime',
      'keyword research',
      'search engine',
      'sıralama',
      'backlink',
      'serp',
    ],
    negativeEvidence: ['csv veri', 'dashboard grafik', 'blog yazısı üret'],
  },
  'customer-support': {
    queryGroups: [
      ['destek', 'support', 'helpdesk', 'ticket', 'müşteri hizmet'],
      ['otomasyon', 'bot', 'yanıt', 'automation', 'reply', 'chat', 'asistan'],
    ],
    evidence: [
      'müşteri destek',
      'customer support',
      'destek botu',
      'ticket',
      'helpdesk',
      'canlı sohbet',
      'support automation',
    ],
    negativeEvidence: ['satış pipeline', 'crm lead', 'e-posta kampanya'],
  },
  'ecommerce-copy': {
    queryGroups: [
      ['ürün', 'product', 'e-ticaret', 'ecommerce', 'mağaza', 'shop'],
      ['açıklama', 'description', 'listing', 'başlık', 'title', 'kopya', 'copy'],
    ],
    evidence: [
      'ürün açıklaması',
      'product description',
      'ürün başlığı',
      'e-ticaret içerik',
      'product listing',
      'mağaza optimizasyon',
      'shopify',
    ],
    negativeEvidence: ['seo sıralama raporu', 'blog makale', 'toplantı özeti'],
  },
  'sales-crm': {
    queryGroups: [
      ['satış', 'sales', 'crm', 'lead', 'pipeline'],
      ['yönet', 'otomasyon', 'takip', 'manage', 'track', 'forecast', 'tahmin', 'araç'],
    ],
    evidence: [
      'satış crm',
      'lead yönetimi',
      'pipeline',
      'satış otomasyon',
      'crm',
      'müşteri adayı',
      'sales forecast',
    ],
    negativeEvidence: ['müşteri destek ticket', 'ürün açıklaması', 'blog yaz'],
  },
  'learning-tutor': {
    queryGroups: [
      ['öğren', 'learn', 'eğitim', 'education', 'ders', 'kurs', 'course', 'tutor'],
      ['asistan', 'yardım', 'araç', 'assistant', 'help', 'tool', 'çalış', 'study'],
    ],
    evidence: [
      'öğrenme asistan',
      'eğitim platform',
      'kişisel tutor',
      'ders anlat',
      'study assistant',
      'kurs oluştur',
      'learning',
    ],
    negativeEvidence: ['kod yaz asistan', 'ide', 'programlama dillerini öğreten geliştirici'],
  },
  'legal-review': {
    queryGroups: [
      ['hukuk', 'legal', 'sözleşme', 'contract', 'yasal'],
      ['incele', 'review', 'analiz', 'analiz et', 'kontrol', 'uyumluluk', 'compliance'],
    ],
    evidence: [
      'sözleşme inceleme',
      'contract review',
      'yasal analiz',
      'hukuki',
      'uyumluluk',
      'compliance',
      'kvkk',
      'gdpr',
    ],
    negativeEvidence: ['pazarlama metni', 'blog yaz', 'görsel üret'],
  },
  'three-d-generation': {
    queryGroups: [
      ['3d', 'üç boyut', 'avatar', 'mesh', 'model'],
      ['üret', 'oluştur', 'yap', 'generate', 'create', 'make', 'render'],
    ],
    evidence: [
      '3d model',
      '3d üret',
      'avatar oluştur',
      'dijital insan',
      'text to 3d',
      'mesh',
      '3d generation',
    ],
    negativeEvidence: ['2d görsel', 'logo tasarım', 'video animasyon montaj'],
  },
};
