/**
 * Pack runners — platform-generated first outputs.
 * LLM chain: Partner API → Gemini → deterministic local fallback.
 *
 * Runnable: content-studio, sales-outreach, meeting-to-action, social-launch,
 * pitch-deck, seo-brief, support-kit, code-scaffold, legal-review, research-brief
 */

import { getJobPackById, isRunnablePack, RUNNABLE_PACK_IDS } from './jobPacks';
import { callLlmJson } from './partnerRunner';

export { isRunnablePack, RUNNABLE_PACK_IDS };

function safeBrief(brief, locale, fallbackTr, fallbackEn) {
  const topic = String(brief || '')
    .trim()
    .slice(0, 280);
  return topic || (locale === 'en' ? fallbackEn : fallbackTr);
}

/** Partner API first, then Gemini. Returns { data, source }. */
async function callProviderJson(prompt) {
  return callLlmJson(prompt);
}

// --- content-studio ---

export function buildLocalContentStudioRun(brief, locale = 'tr') {
  const safeTopic = safeBrief(
    brief,
    locale,
    'Küçük ekipler için AI araçları',
    'AI tools for small teams'
  );

  if (locale === 'en') {
    return {
      packId: 'content-studio',
      goal: 'content-writing',
      bridge: 'runner',
      draft: `# ${safeTopic}

## Why it matters
Teams waste hours switching between AI tools. A clear workflow beats collecting another subscription.

## Practical outline
1. Define the job you need finished this week.
2. Pick one writing tool, one image tool, and one SEO checker.
3. Produce a draft, one visual, and a title/meta pair in a single session.

## Next step
Paste this draft into your preferred editor, generate a cover with the image prompt below, then publish with the SEO fields.

---
Generated by aikeşif content-studio pack runner (local fallback).`,
      imagePrompt: `Clean editorial cover image for an article about "${safeTopic}", minimal flat illustration, soft violet and cyan accents, lots of negative space, no text, 16:9`,
      seo: {
        title: `${safeTopic} | Practical guide`,
        meta: `A practical guide on ${safeTopic}: workflow, tools, and a first deliverable you can ship today.`,
        keywords: [
          safeTopic.split(' ').slice(0, 4).join(' '),
          'AI tools',
          'workflow',
          'productivity',
        ],
      },
    };
  }

  return {
    packId: 'content-studio',
    goal: 'content-writing',
    bridge: 'runner',
    draft: `# ${safeTopic}

## Neden önemli?
Ekipler AI araçları arasında gezinerek saat kaybediyor. Yeni abonelik toplamak yerine net bir iş akışı kazanır.

## Pratik iskelet
1. Bu hafta bitmesi gereken işi tek cümlede yaz.
2. Bir yazı aracı, bir görsel aracı, bir SEO kontrolü seç.
3. Aynı oturumda taslak + bir görsel + title/meta üret.

## Sonraki adım
Bu taslağı editörüne al, aşağıdaki görsel promptu ile kapak üret, SEO alanlarıyla yayınla.

---
aikeşif içerik stüdyosu paketi runner çıktısı (yerel yedek).`,
    imagePrompt: `"${safeTopic}" konulu editoryal kapak görseli, minimal düz illüstrasyon, yumuşak mor ve camgöbeği tonlar, bol boş alan, metin yok, 16:9`,
    seo: {
      title: `${safeTopic} | Pratik rehber`,
      meta: `${safeTopic} hakkında pratik rehber: iş akışı, araç seçimi ve bugün teslim edebileceğin ilk çıktı.`,
      keywords: [
        safeTopic.split(' ').slice(0, 4).join(' '),
        'AI araçları',
        'iş akışı',
        'üretkenlik',
      ],
    },
  };
}

export function formatContentStudioArtifact(run, locale = 'tr') {
  if (!run) return '';
  const kw = Array.isArray(run.seo?.keywords) ? run.seo.keywords.join(', ') : '';
  if (locale === 'en') {
    return `${run.draft}

---
## Image prompt
${run.imagePrompt}

## SEO
Title: ${run.seo?.title || ''}
Meta: ${run.seo?.meta || ''}
Keywords: ${kw}`;
  }
  return `${run.draft}

---
## Görsel prompt
${run.imagePrompt}

## SEO
Title: ${run.seo?.title || ''}
Meta: ${run.seo?.meta || ''}
Anahtar kelimeler: ${kw}`;
}

export async function runContentStudioPack(brief, locale = 'tr') {
  if (!getJobPackById('content-studio', locale)) throw new Error('unknown_pack');

  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a content studio pack runner for an AI tools platform.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "draft": "markdown blog draft 400-700 words in ${lang}",
  "imagePrompt": "one image generation prompt in ${lang}",
  "seo": {
    "title": "SEO title",
    "meta": "meta description",
    "keywords": ["k1","k2","k3"]
  }
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) {
    return { ...buildLocalContentStudioRun(brief, locale), source: 'local' };
  }

  const draft = String(parsed.draft || '').trim();
  if (draft.length < 200) {
    return { ...buildLocalContentStudioRun(brief, locale), source: 'local-fallback' };
  }

  return {
    packId: 'content-studio',
    goal: 'content-writing',
    bridge: 'runner',
    draft,
    imagePrompt: String(parsed.imagePrompt || '')
      .trim()
      .slice(0, 800),
    seo: {
      title: String(parsed.seo?.title || '')
        .trim()
        .slice(0, 120),
      meta: String(parsed.seo?.meta || '')
        .trim()
        .slice(0, 220),
      keywords: Array.isArray(parsed.seo?.keywords)
        ? parsed.seo.keywords.map((k) => String(k).slice(0, 40)).slice(0, 8)
        : [],
    },
    source: llmSource || 'provider',
  };
}

// --- sales-outreach ---

export function buildLocalSalesOutreachRun(brief, locale = 'tr') {
  const offer = safeBrief(
    brief,
    locale,
    'B2B AI keşif platformu demo',
    'B2B AI discovery platform demo'
  );

  if (locale === 'en') {
    return {
      packId: 'sales-outreach',
      goal: 'email-writing',
      bridge: 'runner',
      subjects: [
        `Quick idea for ${offer}`,
        `15 minutes on ${offer}?`,
        `Saw your team might need ${offer}`,
      ],
      sequence: [
        {
          day: 0,
          label: 'Email 1 — opener',
          body: `Subject: Quick idea for ${offer}

Hi {{first_name}},

I help teams cut the time they spend evaluating AI tools. We put together a short workflow around ${offer} that usually surfaces a first usable output in under 30 minutes.

Would a 15-minute walkthrough next week be useful?

Best,
{{sender}}`,
        },
        {
          day: 3,
          label: 'Email 2 — value',
          body: `Subject: Re: ${offer}

Hi {{first_name}},

Quick follow-up: teams using this flow usually replace 3–4 tool trials with one guided pack (write → visual → next step).

Happy to send a one-pager if email is easier than a call.

Best,
{{sender}}`,
        },
        {
          day: 7,
          label: 'Email 3 — close',
          body: `Subject: Close the loop on ${offer}

Hi {{first_name}},

I'll close the loop here. If exploring ${offer} is on your list later this quarter, just reply "later" and I'll send a short checklist.

Thanks,
{{sender}}`,
        },
      ],
      crmStages: ['New lead', 'Contacted', 'Demo booked', 'Won / Lost'],
      followUpRules: [
        'If no reply in 3 days → Email 2',
        'If no reply in 7 days → Email 3 then pause',
        'If positive reply → move to Demo booked same day',
      ],
    };
  }

  return {
    packId: 'sales-outreach',
    goal: 'email-writing',
    bridge: 'runner',
    subjects: [
      `${offer} için kısa bir fikir`,
      `${offer} — 15 dk uygun mu?`,
      `Ekibiniz ${offer} tarafında mı?`,
    ],
    sequence: [
      {
        day: 0,
        label: 'E-posta 1 — açılış',
        body: `Konu: ${offer} için kısa bir fikir

Merhaba {{first_name}},

AI araçlarını denemek için harcanan süreyi kısaltan ekiplerle çalışıyorum. ${offer} etrafında genelde 30 dakikada ilk somut çıktıyı veren bir akış kuruyoruz.

Gelecek hafta 15 dakikalık bir bakış faydalı olur mu?

Saygılarımla,
{{sender}}`,
      },
      {
        day: 3,
        label: 'E-posta 2 — değer',
        body: `Konu: Re: ${offer}

Merhaba {{first_name}},

Kısa takip: Bu akışı kullanan ekipler genelde 3–4 araç denemesini tek rehberli paketle değiştiriyor (yaz → görsel → sonraki adım).

Görüşme yerine tek sayfalık özet de gönderebilirim.

Saygılarımla,
{{sender}}`,
      },
      {
        day: 7,
        label: 'E-posta 3 — kapanış',
        body: `Konu: ${offer} — döngüyü kapatayım

Merhaba {{first_name}},

Bu turda döngüyü kapatıyorum. ${offer} bu çeyrekte gündeme gelirse "sonra" yazman yeterli; kısa bir kontrol listesi yollarım.

Teşekkürler,
{{sender}}`,
      },
    ],
    crmStages: ['Yeni lead', 'İletişime geçildi', 'Demo planlandı', 'Kazanıldı / Kaybedildi'],
    followUpRules: [
      '3 günde yanıt yok → E-posta 2',
      '7 günde yanıt yok → E-posta 3 sonra dur',
      'Olumlu yanıt → aynı gün Demo planlandı',
    ],
  };
}

export function formatSalesOutreachArtifact(run, locale = 'tr') {
  if (!run) return '';
  const subjects = (run.subjects || []).map((s, i) => `${i + 1}. ${s}`).join('\n');
  const sequence = (run.sequence || [])
    .map((step) => `### ${step.label} (D+${step.day})\n\n${step.body}`)
    .join('\n\n');
  const stages = (run.crmStages || []).map((s, i) => `${i + 1}. ${s}`).join('\n');
  const rules = (run.followUpRules || []).map((r) => `- ${r}`).join('\n');

  if (locale === 'en') {
    return `# Sales outreach pack

## Subject lines
${subjects}

## Sequence
${sequence}

## CRM stages
${stages}

## Follow-up rules
${rules}

---
Generated by aikeşif sales-outreach pack runner.`;
  }

  return `# Satış outreach paketi

## Konu satırları
${subjects}

## Seri
${sequence}

## CRM aşamaları
${stages}

## Takip kuralları
${rules}

---
aikeşif sales-outreach pack runner çıktısı.`;
}

export async function runSalesOutreachPack(brief, locale = 'tr') {
  if (!getJobPackById('sales-outreach', locale)) throw new Error('unknown_pack');

  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a B2B sales outreach pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON in ${lang} for user-facing strings:
{
  "subjects": ["subject1","subject2","subject3"],
  "sequence": [
    { "day": 0, "label": "Email 1", "body": "full email with Subject: line" },
    { "day": 3, "label": "Email 2", "body": "..." },
    { "day": 7, "label": "Email 3", "body": "..." }
  ],
  "crmStages": ["stage1","stage2","stage3","stage4"],
  "followUpRules": ["rule1","rule2","rule3"]
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed || !Array.isArray(parsed.sequence) || parsed.sequence.length < 2) {
    return { ...buildLocalSalesOutreachRun(brief, locale), source: 'local' };
  }

  return {
    packId: 'sales-outreach',
    goal: 'email-writing',
    bridge: 'runner',
    subjects: Array.isArray(parsed.subjects)
      ? parsed.subjects.map((s) => String(s).slice(0, 120)).slice(0, 5)
      : [],
    sequence: parsed.sequence.slice(0, 5).map((step, index) => ({
      day: Number.isFinite(Number(step.day)) ? Number(step.day) : index * 3,
      label: String(step.label || `Email ${index + 1}`).slice(0, 80),
      body: String(step.body || '').slice(0, 2000),
    })),
    crmStages: Array.isArray(parsed.crmStages)
      ? parsed.crmStages.map((s) => String(s).slice(0, 60)).slice(0, 6)
      : [],
    followUpRules: Array.isArray(parsed.followUpRules)
      ? parsed.followUpRules.map((s) => String(s).slice(0, 160)).slice(0, 6)
      : [],
    source: llmSource || 'provider',
  };
}

// --- meeting-to-action ---

export function buildLocalMeetingToActionRun(brief, locale = 'tr') {
  const topic = safeBrief(brief, locale, 'Haftalık ürün senkronu', 'Weekly product sync');

  if (locale === 'en') {
    return {
      packId: 'meeting-to-action',
      goal: 'meeting-notes',
      bridge: 'runner',
      summary: `Meeting: ${topic}
Attendees: {{names}}
Duration: {{minutes}} min

### Summary
- Aligned on the main goal for ${topic}.
- Risks: unclear owner for the next deliverable; tool sprawl.
- Decision: ship one guided workflow this week instead of evaluating more tools.

### Decisions
1. Use a single pack/workflow for the next deliverable.
2. Capture first_result before adding another SaaS seat.`,
      actions: [
        {
          owner: '{{owner_1}}',
          task: `Draft the first deliverable for ${topic}`,
          due: 'D+2',
        },
        {
          owner: '{{owner_2}}',
          task: 'Connect meeting summary → task tracker automation and run a test',
          due: 'D+3',
        },
        {
          owner: '{{owner_1}}',
          task: 'Share first_result link/screenshot with stakeholders',
          due: 'D+4',
        },
      ],
      automationMap: {
        trigger: 'Meeting recording uploaded / transcript ready',
        steps: [
          'Transcribe + summarize with AI notes tool',
          'Extract action items to structured list',
          'Create tasks in tracker (Asana/Jira/Linear/Notion)',
          'Post summary to Slack/Teams channel',
        ],
        successCriteria: 'Test run moves 1 real action item into the tracker with owner + due date',
      },
    };
  }

  return {
    packId: 'meeting-to-action',
    goal: 'meeting-notes',
    bridge: 'runner',
    summary: `Toplantı: ${topic}
Katılımcılar: {{names}}
Süre: {{minutes}} dk

### Özet
- ${topic} için ana hedef netleştirildi.
- Riskler: sonraki teslimatta sahip belirsiz; araç dağınıklığı.
- Karar: bu hafta yeni araç denemek yerine tek rehberli akış çıkarılacak.

### Kararlar
1. Sonraki teslimat için tek paket/iş akışı kullanılacak.
2. Yeni SaaS koltuğu eklemeden önce first_result alınacak.`,
    actions: [
      {
        owner: '{{owner_1}}',
        task: `${topic} için ilk teslimat taslağını çıkar`,
        due: 'D+2',
      },
      {
        owner: '{{owner_2}}',
        task: 'Toplantı özeti → görev aracı otomasyonunu bağla ve test et',
        due: 'D+3',
      },
      {
        owner: '{{owner_1}}',
        task: 'first_result link/ekran görüntüsünü paydaşlara ilet',
        due: 'D+4',
      },
    ],
    automationMap: {
      trigger: 'Toplantı kaydı yüklendi / transkript hazır',
      steps: [
        'AI not aracı ile transkript + özet',
        'Aksiyon maddelerini yapılandırılmış listeye çıkar',
        'Görev aracında kart oluştur (Asana/Jira/Linear/Notion)',
        'Özeti Slack/Teams kanalına gönder',
      ],
      successCriteria: 'Test çalıştırması 1 gerçek aksiyonu sahip + son tarih ile tracker’a taşır',
    },
  };
}

export function formatMeetingToActionArtifact(run, locale = 'tr') {
  if (!run) return '';
  const actions = (run.actions || [])
    .map((a, i) => `${i + 1}. [${a.due || 'TBD'}] ${a.owner || '—'} — ${a.task || ''}`)
    .join('\n');
  const steps = (run.automationMap?.steps || []).map((s, i) => `${i + 1}. ${s}`).join('\n');

  if (locale === 'en') {
    return `# Meeting to action pack

## Summary
${run.summary || ''}

## Action items
${actions}

## Automation map
Trigger: ${run.automationMap?.trigger || ''}

Steps:
${steps}

Success: ${run.automationMap?.successCriteria || ''}

---
Generated by aikeşif meeting-to-action pack runner.`;
  }

  return `# Toplantıdan aksiyona paketi

## Özet
${run.summary || ''}

## Aksiyon maddeleri
${actions}

## Otomasyon haritası
Tetikleyici: ${run.automationMap?.trigger || ''}

Adımlar:
${steps}

Başarı: ${run.automationMap?.successCriteria || ''}

---
aikeşif meeting-to-action pack runner çıktısı.`;
}

export async function runMeetingToActionPack(brief, locale = 'tr') {
  if (!getJobPackById('meeting-to-action', locale)) throw new Error('unknown_pack');

  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a meeting-to-action pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON; user-facing strings in ${lang}:
{
  "summary": "meeting summary with decisions",
  "actions": [
    { "owner": "role or name", "task": "task", "due": "D+2" }
  ],
  "automationMap": {
    "trigger": "when this starts",
    "steps": ["step1","step2","step3"],
    "successCriteria": "what success looks like"
  }
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed || !String(parsed.summary || '').trim()) {
    return { ...buildLocalMeetingToActionRun(brief, locale), source: 'local' };
  }

  return {
    packId: 'meeting-to-action',
    goal: 'meeting-notes',
    bridge: 'runner',
    summary: String(parsed.summary || '').slice(0, 3000),
    actions: Array.isArray(parsed.actions)
      ? parsed.actions.slice(0, 8).map((a) => ({
          owner: String(a.owner || '').slice(0, 60),
          task: String(a.task || '').slice(0, 200),
          due: String(a.due || '').slice(0, 20),
        }))
      : [],
    automationMap: {
      trigger: String(parsed.automationMap?.trigger || '').slice(0, 200),
      steps: Array.isArray(parsed.automationMap?.steps)
        ? parsed.automationMap.steps.map((s) => String(s).slice(0, 160)).slice(0, 8)
        : [],
      successCriteria: String(parsed.automationMap?.successCriteria || '').slice(0, 240),
    },
    source: llmSource || 'provider',
  };
}

// --- social-launch ---

export function buildLocalSocialLaunchRun(brief, locale = 'tr') {
  const campaign = safeBrief(brief, locale, 'Yeni AI özellik lansmanı', 'New AI feature launch');

  if (locale === 'en') {
    return {
      packId: 'social-launch',
      goal: 'content-writing',
      bridge: 'runner',
      calendar: [
        { day: 'Mon', theme: 'Tease', channel: 'LinkedIn + X' },
        { day: 'Wed', theme: 'Demo / how-it-works', channel: 'LinkedIn + Instagram' },
        { day: 'Fri', theme: 'Social proof + CTA', channel: 'X + newsletter teaser' },
      ],
      posts: [
        {
          channel: 'LinkedIn',
          body: `We're shipping a guided pack for ${campaign}.

Not another tool list — a workflow that gets you to a first result.

If you evaluate AI tools for your team, this is for you.

#AI #ProductLaunch`,
        },
        {
          channel: 'X',
          body: `Stop collecting AI tabs.

${campaign}: pick the job → run the pack → first output in one session.

Thread ↓`,
        },
        {
          channel: 'Instagram',
          body: `Caption: ${campaign} in 3 slides
1) The pain (tool sprawl)
2) The pack (steps)
3) The CTA (try the first run)

Save this if you're building with AI this week.`,
        },
      ],
      imagePrompts: [
        `Square social graphic for "${campaign}", bold minimal type space left blank, violet gradient, clean icons, no tiny text, 1:1`,
        `Story/reel cover for "${campaign}", vertical 9:16, high contrast, one hero icon, empty area for caption overlay`,
      ],
      schedulePlan: [
        'Mon 10:00 LinkedIn tease',
        'Mon 11:00 X short post + link',
        'Wed 12:00 Instagram carousel',
        'Fri 09:30 X proof + CTA',
      ],
    };
  }

  return {
    packId: 'social-launch',
    goal: 'content-writing',
    bridge: 'runner',
    calendar: [
      { day: 'Pzt', theme: 'Teaser', channel: 'LinkedIn + X' },
      { day: 'Çar', theme: 'Demo / nasıl çalışır', channel: 'LinkedIn + Instagram' },
      { day: 'Cum', theme: 'Sosyal kanıt + CTA', channel: 'X + bülten teaser' },
    ],
    posts: [
      {
        channel: 'LinkedIn',
        body: `${campaign} için rehberli bir paket çıkardık.

Yeni bir araç listesi değil — ilk sonuca götüren bir iş akışı.

Ekibin için AI aracı seçiyorsan bu senlik.

#AI #ÜrünLansmanı`,
      },
      {
        channel: 'X',
        body: `AI sekmelerini biriktirmeyi bırak.

${campaign}: işi seç → paketi çalıştır → aynı oturumda ilk çıktı.

Thread ↓`,
      },
      {
        channel: 'Instagram',
        body: `Caption: ${campaign} — 3 slayt
1) Acı (araç dağınıklığı)
2) Paket (adımlar)
3) CTA (ilk koşuyu dene)

Bu hafta AI ile üretenler kaydetsin.`,
      },
    ],
    imagePrompts: [
      `"${campaign}" için kare sosyal grafik, cesur minimal, sol tarafta boş alan, mor gradient, temiz ikonlar, minik yazı yok, 1:1`,
      `"${campaign}" story/reel kapağı, dikey 9:16, yüksek kontrast, tek hero ikon, caption için boş alan`,
    ],
    schedulePlan: [
      'Pzt 10:00 LinkedIn teaser',
      'Pzt 11:00 X kısa post + link',
      'Çar 12:00 Instagram carousel',
      'Cum 09:30 X kanıt + CTA',
    ],
  };
}

export function formatSocialLaunchArtifact(run, locale = 'tr') {
  if (!run) return '';
  const calendar = (run.calendar || [])
    .map((c) => `- ${c.day}: ${c.theme} (${c.channel})`)
    .join('\n');
  const posts = (run.posts || []).map((p) => `### ${p.channel}\n\n${p.body}`).join('\n\n');
  const images = (run.imagePrompts || []).map((p, i) => `${i + 1}. ${p}`).join('\n');
  const schedule = (run.schedulePlan || []).map((s) => `- ${s}`).join('\n');

  if (locale === 'en') {
    return `# Social launch pack

## Calendar
${calendar}

## Posts
${posts}

## Image prompts
${images}

## Schedule
${schedule}

---
Generated by aikeşif social-launch pack runner.`;
  }

  return `# Sosyal medya lansman paketi

## Takvim
${calendar}

## Postlar
${posts}

## Görsel promptlar
${images}

## Zamanlama
${schedule}

---
aikeşif social-launch pack runner çıktısı.`;
}

export async function runSocialLaunchPack(brief, locale = 'tr') {
  if (!getJobPackById('social-launch', locale)) throw new Error('unknown_pack');

  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a social media launch pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON; user-facing strings in ${lang}:
{
  "calendar": [{ "day": "Mon", "theme": "...", "channel": "LinkedIn + X" }],
  "posts": [{ "channel": "LinkedIn", "body": "full post text" }],
  "imagePrompts": ["prompt1","prompt2"],
  "schedulePlan": ["Mon 10:00 ..."]
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed || !Array.isArray(parsed.posts) || parsed.posts.length < 2) {
    return { ...buildLocalSocialLaunchRun(brief, locale), source: 'local' };
  }

  return {
    packId: 'social-launch',
    goal: 'content-writing',
    bridge: 'runner',
    calendar: Array.isArray(parsed.calendar)
      ? parsed.calendar.slice(0, 7).map((c) => ({
          day: String(c.day || '').slice(0, 20),
          theme: String(c.theme || '').slice(0, 80),
          channel: String(c.channel || '').slice(0, 60),
        }))
      : [],
    posts: parsed.posts.slice(0, 6).map((p) => ({
      channel: String(p.channel || '').slice(0, 40),
      body: String(p.body || '').slice(0, 1200),
    })),
    imagePrompts: Array.isArray(parsed.imagePrompts)
      ? parsed.imagePrompts.map((p) => String(p).slice(0, 400)).slice(0, 4)
      : [],
    schedulePlan: Array.isArray(parsed.schedulePlan)
      ? parsed.schedulePlan.map((s) => String(s).slice(0, 120)).slice(0, 8)
      : [],
    source: llmSource || 'provider',
  };
}

// --- pitch-deck ---

export function buildLocalPitchDeckRun(brief, locale = 'tr') {
  const product = safeBrief(brief, locale, 'aikeşif iş paketleri', 'aikeşif job packs');

  if (locale === 'en') {
    return {
      packId: 'pitch-deck',
      goal: 'presentation-creation',
      bridge: 'runner',
      narrative: `Investor narrative for ${product}: tool sprawl → guided job packs → first result in-session → data moat on completion metrics.`,
      slides: [
        {
          title: 'Problem',
          bullets: [
            'Teams juggle 5+ AI subscriptions',
            'Directories stop at the link click',
            'No shared metric for “job done”',
          ],
        },
        {
          title: 'Solution',
          bullets: [
            `${product}: pack → plan → first output`,
            'Kâşif + Workmind orchestration',
            'Funnel: stated → first_result → done',
          ],
        },
        {
          title: 'Product',
          bullets: [
            'Job packs by use case',
            'On-platform runners',
            'Catalog-grounded recommendations',
          ],
        },
        {
          title: 'Market',
          bullets: [
            'SMB + creators adopting AI weekly',
            'TR niche + global English UI',
            'Adjacent: automation & content stacks',
          ],
        },
        {
          title: 'Go-to-market',
          bullets: ['SEO on intent queries', 'Pack-led activation', 'Pro gate after free quota'],
        },
        {
          title: 'Business model',
          bullets: ['Pro membership', 'Pack orchestration layer', 'Future partner runner margin'],
        },
        {
          title: 'Traction plan',
          bullets: [
            'first_result rate by pack_id',
            'Time-to-first-result',
            'Runner vs paste bridge mix',
          ],
        },
        {
          title: 'Ask',
          bullets: [
            'Capital for pack coverage + integrations',
            'Design partners for 2 verticals',
            '12-month roadmap',
          ],
        },
      ],
      visualPrompts: [
        `Clean pitch cover slide visual for "${product}", abstract nodes connected, violet/cyan, no text, 16:9`,
        `Simple funnel diagram background for job completion metrics, minimal geometric, 16:9`,
      ],
      speakerNotes: [
        'Open with a personal story of subscription fatigue.',
        'Demo one pack end-to-end in under 2 minutes.',
        'Close on the data advantage: we measure job completion, not clicks.',
      ],
    };
  }

  return {
    packId: 'pitch-deck',
    goal: 'presentation-creation',
    bridge: 'runner',
    narrative: `${product} yatırımcı anlatısı: araç dağınıklığı → rehberli iş paketleri → oturum içi ilk sonuç → tamamlanma metriklerinde veri avantajı.`,
    slides: [
      {
        title: 'Problem',
        bullets: [
          'Ekipler 5+ AI aboneliği juggle ediyor',
          'Dizinler tıklamada bitiyor',
          '“İş bitti” ortak metriği yok',
        ],
      },
      {
        title: 'Çözüm',
        bullets: [
          `${product}: paket → plan → ilk çıktı`,
          'Kâşif + Workmind orkestrasyonu',
          'Huni: niyet → first_result → bitti',
        ],
      },
      {
        title: 'Ürün',
        bullets: [
          'Kullanım senaryosuna göre paketler',
          'Platform içi runner’lar',
          'Kataloga dayalı öneriler',
        ],
      },
      {
        title: 'Pazar',
        bullets: [
          'SMB + üreticiler her hafta AI deniyor',
          'TR niş + İngilizce UI',
          'Yan pazar: otomasyon ve içerik yığınları',
        ],
      },
      {
        title: 'GTM',
        bullets: [
          'Niyet sorgularında SEO',
          'Paket odaklı aktivasyon',
          'Ücretsiz kota sonrası Pro gate',
        ],
      },
      {
        title: 'Model',
        bullets: ['Pro üyelik', 'Paket orkestrasyon katmanı', 'İleride partner runner marjı'],
      },
      {
        title: 'Traction planı',
        bullets: [
          'pack_id first_result oranı',
          'Time-to-first-result',
          'Runner vs paste bridge karışımı',
        ],
      },
      {
        title: 'Ask',
        bullets: [
          'Paket kapsamı + entegrasyon sermayesi',
          '2 dikeyde design partner',
          '12 aylık yol haritası',
        ],
      },
    ],
    visualPrompts: [
      `"${product}" pitch kapak görseli, bağlı soyut düğümler, mor/camgöbeği, metin yok, 16:9`,
      `İş bitirme metrikleri için sade huni diyagram arka planı, minimal geometrik, 16:9`,
    ],
    speakerNotes: [
      'Abonelik yorgunluğu hikâyesiyle aç.',
      'Bir paketi 2 dakikada uçtan uca göster.',
      'Kapanış: tıklama değil, görev tamamlama verisi.',
    ],
  };
}

export function formatPitchDeckArtifact(run, locale = 'tr') {
  if (!run) return '';
  const slides = (run.slides || [])
    .map((s, i) => {
      const bullets = (s.bullets || []).map((b) => `  - ${b}`).join('\n');
      return `### ${i + 1}. ${s.title}\n${bullets}`;
    })
    .join('\n\n');
  const visuals = (run.visualPrompts || []).map((p, i) => `${i + 1}. ${p}`).join('\n');
  const notes = (run.speakerNotes || []).map((n, i) => `${i + 1}. ${n}`).join('\n');

  if (locale === 'en') {
    return `# Pitch deck pack

## Narrative
${run.narrative || ''}

## Slides
${slides}

## Visual prompts
${visuals}

## Speaker notes
${notes}

---
Generated by aikeşif pitch-deck pack runner.`;
  }

  return `# Pitch deck paketi

## Anlatı
${run.narrative || ''}

## Slaytlar
${slides}

## Görsel promptlar
${visuals}

## Sunum notları
${notes}

---
aikeşif pitch-deck pack runner çıktısı.`;
}

export async function runPitchDeckPack(brief, locale = 'tr') {
  if (!getJobPackById('pitch-deck', locale)) throw new Error('unknown_pack');

  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a pitch deck pack runner for an AI tools platform.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON; user-facing strings in ${lang}:
{
  "narrative": "one paragraph investor narrative",
  "slides": [{ "title": "Problem", "bullets": ["...","..."] }],
  "visualPrompts": ["prompt1","prompt2"],
  "speakerNotes": ["note1","note2"]
}
Aim for 7-10 slides.`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed || !Array.isArray(parsed.slides) || parsed.slides.length < 5) {
    return { ...buildLocalPitchDeckRun(brief, locale), source: 'local' };
  }

  return {
    packId: 'pitch-deck',
    goal: 'presentation-creation',
    bridge: 'runner',
    narrative: String(parsed.narrative || '').slice(0, 800),
    slides: parsed.slides.slice(0, 12).map((s) => ({
      title: String(s.title || '').slice(0, 80),
      bullets: Array.isArray(s.bullets)
        ? s.bullets.map((b) => String(b).slice(0, 160)).slice(0, 6)
        : [],
    })),
    visualPrompts: Array.isArray(parsed.visualPrompts)
      ? parsed.visualPrompts.map((p) => String(p).slice(0, 400)).slice(0, 4)
      : [],
    speakerNotes: Array.isArray(parsed.speakerNotes)
      ? parsed.speakerNotes.map((n) => String(n).slice(0, 200)).slice(0, 8)
      : [],
    source: llmSource || 'provider',
  };
}

// --- seo-brief (multi-step) ---

export function buildLocalSeoBriefRun(brief, locale = 'tr') {
  const topic = safeBrief(
    brief,
    locale,
    'küçük ekipler için AI araçları',
    'AI tools for small teams'
  );
  const primary = locale === 'en' ? `best ${topic}` : `en iyi ${topic}`;
  const secondary =
    locale === 'en'
      ? [`${topic} comparison`, `${topic} free tools`, `how to choose ${topic}`]
      : [`${topic} karşılaştırma`, `ücretsiz ${topic}`, `${topic} nasıl seçilir`];

  if (locale === 'en') {
    const steps = [
      {
        id: 'keywords',
        title: 'Keywords',
        body: `Primary: ${primary}\nSecondary:\n- ${secondary.join('\n- ')}`,
      },
      {
        id: 'outline',
        title: 'H2 outline',
        body: `1. Why ${topic} matters now\n2. Evaluation criteria\n3. Top options overview\n4. Free vs paid trade-offs\n5. Implementation checklist\n6. FAQ`,
      },
      {
        id: 'meta',
        title: 'Title & meta',
        body: `Title: ${primary} (2026 guide)\nMeta: Practical guide to ${topic}: criteria, comparisons, and a short checklist for small teams.`,
      },
      {
        id: 'content-brief',
        title: 'Content brief',
        body: `Audience: operators choosing tools without a big research team.\nAngle: decision framework first, tool names second.\nCTA: try a guided pack / catalog shortlist.\nLength: 900–1200 words.`,
      },
    ];
    return {
      packId: 'seo-brief',
      goal: 'seo-optimization',
      bridge: 'runner',
      keywords: { primary, secondary },
      outline: steps[1].body.split('\n'),
      meta: {
        title: `${primary} (2026 guide)`,
        description: steps[2].body.split('\n')[1]?.replace(/^Meta:\s*/, '') || '',
      },
      contentBrief: steps[3].body,
      steps,
    };
  }

  const steps = [
    {
      id: 'keywords',
      title: 'Anahtar kelimeler',
      body: `Birincil: ${primary}\nİkincil:\n- ${secondary.join('\n- ')}`,
    },
    {
      id: 'outline',
      title: 'H2 iskeleti',
      body: `1. ${topic} neden önemli?\n2. Değerlendirme kriterleri\n3. Öne çıkan seçenekler\n4. Ücretsiz vs ücretli\n5. Uygulama kontrol listesi\n6. SSS`,
    },
    {
      id: 'meta',
      title: 'Title & meta',
      body: `Title: ${primary} (2026 rehberi)\nMeta: ${topic} için pratik rehber: kriterler, karşılaştırma ve küçük ekipler için kısa kontrol listesi.`,
    },
    {
      id: 'content-brief',
      title: 'İçerik brief',
      body: `Kitle: araştırma ekibi olmadan araç seçen operasyon ekipleri.\nAçı: önce karar çerçevesi, sonra araç isimleri.\nCTA: paket / katalog kısa listesi dene.\nUzunluk: 900–1200 kelime.`,
    },
  ];
  return {
    packId: 'seo-brief',
    goal: 'seo-optimization',
    bridge: 'runner',
    keywords: { primary, secondary },
    outline: steps[1].body.split('\n'),
    meta: {
      title: `${primary} (2026 rehberi)`,
      description: steps[2].body.split('\n')[1]?.replace(/^Meta:\s*/, '') || '',
    },
    contentBrief: steps[3].body,
    steps,
  };
}

export function formatSeoBriefArtifact(run, locale = 'tr') {
  if (!run) return '';
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps.map((step, i) => `## ${i + 1}. ${step.title}\n${step.body}`).join('\n\n');
  }
  const kw = [run.keywords?.primary, ...(run.keywords?.secondary || [])].filter(Boolean).join(', ');
  return locale === 'en'
    ? `Keywords: ${kw}\n\nOutline:\n${(run.outline || []).join('\n')}\n\nTitle: ${run.meta?.title || ''}\nMeta: ${run.meta?.description || ''}\n\nBrief:\n${run.contentBrief || ''}`
    : `Anahtar kelimeler: ${kw}\n\nİskelet:\n${(run.outline || []).join('\n')}\n\nTitle: ${run.meta?.title || ''}\nMeta: ${run.meta?.description || ''}\n\nBrief:\n${run.contentBrief || ''}`;
}

export async function runSeoBriefPack(brief, locale = 'tr') {
  if (!getJobPackById('seo-brief', locale)) throw new Error('unknown_pack');
  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are an SEO brief pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "keywords": { "primary": "string", "secondary": ["s1","s2","s3"] },
  "outline": ["H2 1","H2 2","H2 3","H2 4"],
  "meta": { "title": "SEO title", "description": "meta description" },
  "contentBrief": "1 short paragraph content brief in ${lang}",
  "steps": [
    { "id": "keywords", "title": "string", "body": "string" },
    { "id": "outline", "title": "string", "body": "string" },
    { "id": "meta", "title": "string", "body": "string" },
    { "id": "content-brief", "title": "string", "body": "string" }
  ]
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) {
    return { ...buildLocalSeoBriefRun(brief, locale), source: 'local' };
  }

  const primary = String(parsed.keywords?.primary || '').trim();
  if (!primary || primary.length < 3) {
    return { ...buildLocalSeoBriefRun(brief, locale), source: 'local-fallback' };
  }

  const secondary = Array.isArray(parsed.keywords?.secondary)
    ? parsed.keywords.secondary
        .map((s) => String(s || '').trim())
        .filter(Boolean)
        .slice(0, 6)
    : [];
  const outline = Array.isArray(parsed.outline)
    ? parsed.outline
        .map((s) => String(s || '').trim())
        .filter(Boolean)
        .slice(0, 10)
    : [];
  const steps = Array.isArray(parsed.steps)
    ? parsed.steps
        .map((step) => ({
          id: String(step?.id || '')
            .trim()
            .slice(0, 40),
          title: String(step?.title || '')
            .trim()
            .slice(0, 80),
          body: String(step?.body || '')
            .trim()
            .slice(0, 1200),
        }))
        .filter((s) => s.title && s.body)
        .slice(0, 8)
    : [];

  const local = buildLocalSeoBriefRun(brief, locale);
  return {
    packId: 'seo-brief',
    goal: 'seo-optimization',
    bridge: 'runner',
    keywords: { primary: primary.slice(0, 120), secondary },
    outline: outline.length ? outline : local.outline,
    meta: {
      title: String(parsed.meta?.title || local.meta.title)
        .trim()
        .slice(0, 120),
      description: String(parsed.meta?.description || local.meta.description)
        .trim()
        .slice(0, 220),
    },
    contentBrief: String(parsed.contentBrief || local.contentBrief)
      .trim()
      .slice(0, 1200),
    steps: steps.length >= 3 ? steps : local.steps,
    source: llmSource || 'provider',
  };
}

// --- support-kit (multi-step) ---

export function buildLocalSupportKitRun(brief, locale = 'tr') {
  const topic = safeBrief(
    brief,
    locale,
    'abonelik iptali ve iade',
    'subscription cancel and refund'
  );

  if (locale === 'en') {
    const steps = [
      {
        id: 'macros',
        title: 'Macro drafts',
        body: `Macro A — Acknowledge\nHi {{name}}, thanks for writing about ${topic}. I’m on it.\n\nMacro B — Resolve\nHere’s what I did: {{action}}. You should see {{result}} within {{time}}.\n\nMacro C — Close\nAnything else I can help with on ${topic}?`,
      },
      {
        id: 'tone',
        title: 'Tone guide',
        body: 'Warm, plain language, no blame. Prefer short sentences. Confirm next step and timeline.',
      },
      {
        id: 'escalation',
        title: 'Escalation',
        body: `Escalate when: legal risk, payment dispute > $X, repeated failure on ${topic}, or VIP account.\nOwner: L2 support · SLA: 4 business hours · Include ticket id + timeline tried.`,
      },
      {
        id: 'faq',
        title: 'FAQ',
        body: `Q: How long does ${topic} take?\nA: Usually within 1–2 business days after confirmation.\n\nQ: Will I lose access immediately?\nA: Access continues until the end of the current billing period unless noted.`,
      },
    ];
    return {
      packId: 'support-kit',
      goal: 'customer-support',
      bridge: 'runner',
      macros: steps[0].body,
      toneGuide: steps[1].body,
      escalation: steps[2].body,
      faq: steps[3].body,
      steps,
    };
  }

  const steps = [
    {
      id: 'macros',
      title: 'Makro taslakları',
      body: `Makro A — Karşılama\nMerhaba {{name}}, ${topic} hakkında yazdığın için teşekkürler; bakıyorum.\n\nMakro B — Çözüm\nYaptığım: {{action}}. {{result}} durumunu {{time}} içinde görmelisin.\n\nMakro C — Kapanış\n${topic} ile ilgili başka yardımcı olabileceğim bir şey var mı?`,
    },
    {
      id: 'tone',
      title: 'Ton rehberi',
      body: 'Sıcak, sade dil, suçlayıcı olma. Kısa cümleler. Sonraki adımı ve süreyi net yaz.',
    },
    {
      id: 'escalation',
      title: 'Escalation',
      body: `Yükselt: yasal risk, yüksek tutarlı ödeme itirazı, ${topic} tekrarlayan hata, VIP hesap.\nSahip: L2 destek · SLA: 4 iş saati · Ticket id + denenen adımları ekle.`,
    },
    {
      id: 'faq',
      title: 'FAQ',
      body: `S: ${topic} ne kadar sürer?\nC: Onay sonrası genelde 1–2 iş günü.\n\nS: Erişim hemen kesilir mi?\nC: Aksi belirtilmedikçe mevcut dönem sonuna kadar erişim devam eder.`,
    },
  ];
  return {
    packId: 'support-kit',
    goal: 'customer-support',
    bridge: 'runner',
    macros: steps[0].body,
    toneGuide: steps[1].body,
    escalation: steps[2].body,
    faq: steps[3].body,
    steps,
  };
}

export function formatSupportKitArtifact(run, locale = 'tr') {
  if (!run) return '';
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps.map((step, i) => `## ${i + 1}. ${step.title}\n${step.body}`).join('\n\n');
  }
  return [run.macros, run.toneGuide, run.escalation, run.faq].filter(Boolean).join('\n\n---\n\n');
}

export async function runSupportKitPack(brief, locale = 'tr') {
  if (!getJobPackById('support-kit', locale)) throw new Error('unknown_pack');
  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a customer support pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "macros": "3 short reply macros in ${lang}",
  "toneGuide": "short tone rules in ${lang}",
  "escalation": "when/how to escalate in ${lang}",
  "faq": "2 Q&A pairs in ${lang}",
  "steps": [
    { "id": "macros", "title": "string", "body": "string" },
    { "id": "tone", "title": "string", "body": "string" },
    { "id": "escalation", "title": "string", "body": "string" },
    { "id": "faq", "title": "string", "body": "string" }
  ]
}`;

  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) {
    return { ...buildLocalSupportKitRun(brief, locale), source: 'local' };
  }

  const macros = String(parsed.macros || '').trim();
  if (macros.length < 40) {
    return { ...buildLocalSupportKitRun(brief, locale), source: 'local-fallback' };
  }

  const steps = Array.isArray(parsed.steps)
    ? parsed.steps
        .map((step) => ({
          id: String(step?.id || '')
            .trim()
            .slice(0, 40),
          title: String(step?.title || '')
            .trim()
            .slice(0, 80),
          body: String(step?.body || '')
            .trim()
            .slice(0, 1500),
        }))
        .filter((s) => s.title && s.body)
        .slice(0, 8)
    : [];

  const local = buildLocalSupportKitRun(brief, locale);
  return {
    packId: 'support-kit',
    goal: 'customer-support',
    bridge: 'runner',
    macros: macros.slice(0, 2000),
    toneGuide: String(parsed.toneGuide || local.toneGuide)
      .trim()
      .slice(0, 800),
    escalation: String(parsed.escalation || local.escalation)
      .trim()
      .slice(0, 800),
    faq: String(parsed.faq || local.faq)
      .trim()
      .slice(0, 1200),
    steps: steps.length >= 3 ? steps : local.steps,
    source: llmSource || 'provider',
  };
}

// --- code-scaffold (multi-step) ---

export function buildLocalCodeScaffoldRun(brief, locale = 'tr') {
  const topic = safeBrief(brief, locale, 'ücretsiz kota kontrolü API’si', 'free quota check API');

  if (locale === 'en') {
    const steps = [
      {
        id: 'requirements',
        title: 'Requirements',
        body: `Feature: ${topic}\n- Input: userId, window\n- Output: remaining quota + resetAt\n- Non-goals: billing, payment capture`,
      },
      {
        id: 'tree',
        title: 'File tree',
        body: `src/\n  lib/quota.ts\n  app/api/quota/route.ts\n  __tests__/quota.test.ts\n  types/quota.ts`,
      },
      {
        id: 'scaffold',
        title: 'Scaffold code',
        body: `// lib/quota.ts\nexport function remainingQuota(used: number, limit: number) {\n  return Math.max(0, limit - used);\n}\n\n// app/api/quota/route.ts\n// GET → { remaining, resetAt } for ${topic}`,
      },
      {
        id: 'tests',
        title: 'Test plan',
        body: `1. remaining = limit - used (floor 0)\n2. Unauthorized → 401\n3. Missing userId → 400\n4. Window boundary at month start`,
      },
    ];
    return {
      packId: 'code-scaffold',
      goal: 'coding-assistant',
      bridge: 'runner',
      requirements: steps[0].body,
      fileTree: steps[1].body,
      scaffold: steps[2].body,
      testPlan: steps[3].body,
      steps,
    };
  }

  const steps = [
    {
      id: 'requirements',
      title: 'Gereksinim',
      body: `Özellik: ${topic}\n- Girdi: userId, pencere\n- Çıktı: kalan kota + resetAt\n- Kapsam dışı: ödeme alma`,
    },
    {
      id: 'tree',
      title: 'Dosya ağacı',
      body: `src/\n  lib/quota.ts\n  app/api/quota/route.ts\n  __tests__/quota.test.ts\n  types/quota.ts`,
    },
    {
      id: 'scaffold',
      title: 'İskelet kod',
      body: `// lib/quota.ts\nexport function remainingQuota(used: number, limit: number) {\n  return Math.max(0, limit - used);\n}\n\n// app/api/quota/route.ts\n// GET → { remaining, resetAt } — ${topic}`,
    },
    {
      id: 'tests',
      title: 'Test planı',
      body: `1. remaining = limit - used (min 0)\n2. Yetkisiz → 401\n3. userId yok → 400\n4. Ay başı pencere sınırı`,
    },
  ];
  return {
    packId: 'code-scaffold',
    goal: 'coding-assistant',
    bridge: 'runner',
    requirements: steps[0].body,
    fileTree: steps[1].body,
    scaffold: steps[2].body,
    testPlan: steps[3].body,
    steps,
  };
}

export function formatCodeScaffoldArtifact(run) {
  if (!run) return '';
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps.map((step, i) => `## ${i + 1}. ${step.title}\n${step.body}`).join('\n\n');
  }
  return [run.requirements, run.fileTree, run.scaffold, run.testPlan]
    .filter(Boolean)
    .join('\n\n---\n\n');
}

export async function runCodeScaffoldPack(brief, locale = 'tr') {
  if (!getJobPackById('code-scaffold', locale)) throw new Error('unknown_pack');
  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a code scaffold pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "requirements": "short requirements in ${lang}",
  "fileTree": "simple file tree",
  "scaffold": "short starter code snippet",
  "testPlan": "3-5 test cases in ${lang}",
  "steps": [
    { "id": "requirements", "title": "string", "body": "string" },
    { "id": "tree", "title": "string", "body": "string" },
    { "id": "scaffold", "title": "string", "body": "string" },
    { "id": "tests", "title": "string", "body": "string" }
  ]
}`;
  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) return { ...buildLocalCodeScaffoldRun(brief, locale), source: 'local' };
  const requirements = String(parsed.requirements || '').trim();
  if (requirements.length < 20) {
    return { ...buildLocalCodeScaffoldRun(brief, locale), source: 'local-fallback' };
  }
  const steps = Array.isArray(parsed.steps)
    ? parsed.steps
        .map((step) => ({
          id: String(step?.id || '')
            .trim()
            .slice(0, 40),
          title: String(step?.title || '')
            .trim()
            .slice(0, 80),
          body: String(step?.body || '')
            .trim()
            .slice(0, 2000),
        }))
        .filter((s) => s.title && s.body)
        .slice(0, 8)
    : [];
  const local = buildLocalCodeScaffoldRun(brief, locale);
  return {
    packId: 'code-scaffold',
    goal: 'coding-assistant',
    bridge: 'runner',
    requirements: requirements.slice(0, 1200),
    fileTree: String(parsed.fileTree || local.fileTree)
      .trim()
      .slice(0, 1200),
    scaffold: String(parsed.scaffold || local.scaffold)
      .trim()
      .slice(0, 2500),
    testPlan: String(parsed.testPlan || local.testPlan)
      .trim()
      .slice(0, 1200),
    steps: steps.length >= 3 ? steps : local.steps,
    source: llmSource || 'provider',
  };
}

// --- legal-review (multi-step, informational) ---

export function buildLocalLegalReviewRun(brief, locale = 'tr') {
  const topic = safeBrief(brief, locale, 'SaaS abonelik sözleşmesi', 'SaaS subscription agreement');
  const disclaimer =
    locale === 'en'
      ? 'Informational only — not legal advice. Have counsel review.'
      : 'Yalnızca bilgilendirme — hukuki tavsiye değildir. Avukat incelemesi gerekir.';

  if (locale === 'en') {
    const steps = [
      {
        id: 'scope',
        title: 'Scope',
        body: `Document: ${topic}\nFocus: termination, liability, data processing, IP.\n${disclaimer}`,
      },
      {
        id: 'risks',
        title: 'Risk list',
        body: `1. Unlimited liability carve-outs missing\n2. Auto-renew without clear notice\n3. Data processing roles unclear (controller/processor)\n4. Broad IP assignment from customer content`,
      },
      {
        id: 'questions',
        title: 'Question set',
        body: `Q1. Who owns outputs generated with the product?\nQ2. What is the termination notice window?\nQ3. Is there a liability cap and what is excluded?\nQ4. Where is governing law / venue?`,
      },
      {
        id: 'redlines',
        title: 'Redline notes',
        body: `- Cap liability at 12 months fees paid\n- Clarify customer owns their content\n- Require 30-day opt-out before renewal\n- Add DPA reference if personal data is processed`,
      },
    ];
    return {
      packId: 'legal-review',
      goal: 'legal-review',
      bridge: 'runner',
      scope: steps[0].body,
      risks: steps[1].body,
      questions: steps[2].body,
      redlines: steps[3].body,
      disclaimer,
      steps,
    };
  }

  const steps = [
    {
      id: 'scope',
      title: 'Kapsam',
      body: `Belge: ${topic}\nOdak: fesih, sorumluluk, veri işleme, IP.\n${disclaimer}`,
    },
    {
      id: 'risks',
      title: 'Risk listesi',
      body: `1. Sınırsız sorumluluk istisnaları belirsiz\n2. Otomatik yenileme net bildirim yok\n3. Veri işleme rolleri (sorumlu/işleyen) net değil\n4. Müşteri içeriğinde geniş IP devri`,
    },
    {
      id: 'questions',
      title: 'Soru seti',
      body: `S1. Ürünle üretilen çıktının sahibi kim?\nS2. Fesih bildirim süresi nedir?\nS3. Sorumluluk tavanı var mı, istisnalar neler?\nS4. Uygulanacak hukuk / yetkili mahkeme?`,
    },
    {
      id: 'redlines',
      title: 'Redline notları',
      body: `- Sorumluluğu son 12 ay ücretle sınırla\n- Müşteri içeriğinin mülkiyetini netleştir\n- Yenilemeden 30 gün önce çıkış hakkı\n- Kişisel veri varsa DPA referansı ekle`,
    },
  ];
  return {
    packId: 'legal-review',
    goal: 'legal-review',
    bridge: 'runner',
    scope: steps[0].body,
    risks: steps[1].body,
    questions: steps[2].body,
    redlines: steps[3].body,
    disclaimer,
    steps,
  };
}

export function formatLegalReviewArtifact(run) {
  if (!run) return '';
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps.map((step, i) => `## ${i + 1}. ${step.title}\n${step.body}`).join('\n\n');
  }
  return [run.scope, run.risks, run.questions, run.redlines].filter(Boolean).join('\n\n---\n\n');
}

export async function runLegalReviewPack(brief, locale = 'tr') {
  if (!getJobPackById('legal-review', locale)) throw new Error('unknown_pack');
  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a legal review pack runner (informational only, not legal advice).
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "scope": "scope + disclaimer in ${lang}",
  "risks": "bullet risk list in ${lang}",
  "questions": "4 review questions in ${lang}",
  "redlines": "suggested redline notes in ${lang}",
  "steps": [
    { "id": "scope", "title": "string", "body": "string" },
    { "id": "risks", "title": "string", "body": "string" },
    { "id": "questions", "title": "string", "body": "string" },
    { "id": "redlines", "title": "string", "body": "string" }
  ]
}`;
  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) return { ...buildLocalLegalReviewRun(brief, locale), source: 'local' };
  const scope = String(parsed.scope || '').trim();
  if (scope.length < 20) {
    return { ...buildLocalLegalReviewRun(brief, locale), source: 'local-fallback' };
  }
  const steps = Array.isArray(parsed.steps)
    ? parsed.steps
        .map((step) => ({
          id: String(step?.id || '')
            .trim()
            .slice(0, 40),
          title: String(step?.title || '')
            .trim()
            .slice(0, 80),
          body: String(step?.body || '')
            .trim()
            .slice(0, 2000),
        }))
        .filter((s) => s.title && s.body)
        .slice(0, 8)
    : [];
  const local = buildLocalLegalReviewRun(brief, locale);
  return {
    packId: 'legal-review',
    goal: 'legal-review',
    bridge: 'runner',
    scope: scope.slice(0, 1200),
    risks: String(parsed.risks || local.risks)
      .trim()
      .slice(0, 1500),
    questions: String(parsed.questions || local.questions)
      .trim()
      .slice(0, 1500),
    redlines: String(parsed.redlines || local.redlines)
      .trim()
      .slice(0, 1500),
    disclaimer: local.disclaimer,
    steps: steps.length >= 3 ? steps : local.steps,
    source: llmSource || 'provider',
  };
}

// --- research-brief (multi-step) ---

export function buildLocalResearchBriefRun(brief, locale = 'tr') {
  const topic = safeBrief(
    brief,
    locale,
    'KOBİ’lerde AI araç benimsenmesi',
    'AI tool adoption in SMBs'
  );

  if (locale === 'en') {
    const steps = [
      {
        id: 'question',
        title: 'Research question',
        body: `Primary: What drives ${topic}?\nSecondary: Cost, time-to-value, and team skills.`,
      },
      {
        id: 'sources',
        title: 'Sources',
        body: `1. Public reports / surveys\n2. Product pricing pages\n3. 5 customer interviews\n4. Internal usage metrics (if available)`,
      },
      {
        id: 'plan',
        title: 'Analysis plan',
        body: `1. Define segments\n2. Collect 3 data points per segment\n3. Compare time-to-first-value\n4. Rank barriers\n5. Draft recommendation`,
      },
      {
        id: 'findings',
        title: 'Findings template',
        body: `Finding:\nEvidence:\nImplication:\nNext experiment:\nOwner / date:`,
      },
    ];
    return {
      packId: 'research-brief',
      goal: 'data-analysis',
      bridge: 'runner',
      question: steps[0].body,
      sources: steps[1].body,
      analysisPlan: steps[2].body,
      findingsTemplate: steps[3].body,
      steps,
    };
  }

  const steps = [
    {
      id: 'question',
      title: 'Araştırma sorusu',
      body: `Birincil: ${topic}’i ne hızlandırır?\nİkincil: maliyet, time-to-value, ekip becerisi.`,
    },
    {
      id: 'sources',
      title: 'Kaynaklar',
      body: `1. Kamuya açık rapor / anket\n2. Ürün fiyat sayfaları\n3. 5 müşteri görüşmesi\n4. İç kullanım metrikleri (varsa)`,
    },
    {
      id: 'plan',
      title: 'Analiz planı',
      body: `1. Segment tanımla\n2. Segment başına 3 veri noktası\n3. Time-to-first-value karşılaştır\n4. Engelleri sırala\n5. Tavsiye taslağı`,
    },
    {
      id: 'findings',
      title: 'Bulgu şablonu',
      body: `Bulgu:\nKanıt:\nAnlamı:\nSonraki deney:\nSahip / tarih:`,
    },
  ];
  return {
    packId: 'research-brief',
    goal: 'data-analysis',
    bridge: 'runner',
    question: steps[0].body,
    sources: steps[1].body,
    analysisPlan: steps[2].body,
    findingsTemplate: steps[3].body,
    steps,
  };
}

export function formatResearchBriefArtifact(run) {
  if (!run) return '';
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps.map((step, i) => `## ${i + 1}. ${step.title}\n${step.body}`).join('\n\n');
  }
  return [run.question, run.sources, run.analysisPlan, run.findingsTemplate]
    .filter(Boolean)
    .join('\n\n---\n\n');
}

export async function runResearchBriefPack(brief, locale = 'tr') {
  if (!getJobPackById('research-brief', locale)) throw new Error('unknown_pack');
  const lang = locale === 'en' ? 'English' : 'Turkish';
  const prompt = `You are a research brief pack runner.
User brief: ${String(brief || '').slice(0, 500)}
Respond ONLY with valid JSON:
{
  "question": "research questions in ${lang}",
  "sources": "source list in ${lang}",
  "analysisPlan": "analysis steps in ${lang}",
  "findingsTemplate": "findings template in ${lang}",
  "steps": [
    { "id": "question", "title": "string", "body": "string" },
    { "id": "sources", "title": "string", "body": "string" },
    { "id": "plan", "title": "string", "body": "string" },
    { "id": "findings", "title": "string", "body": "string" }
  ]
}`;
  const { data: parsed, source: llmSource } = await callProviderJson(prompt);
  if (!parsed) return { ...buildLocalResearchBriefRun(brief, locale), source: 'local' };
  const question = String(parsed.question || '').trim();
  if (question.length < 12) {
    return { ...buildLocalResearchBriefRun(brief, locale), source: 'local-fallback' };
  }
  const steps = Array.isArray(parsed.steps)
    ? parsed.steps
        .map((step) => ({
          id: String(step?.id || '')
            .trim()
            .slice(0, 40),
          title: String(step?.title || '')
            .trim()
            .slice(0, 80),
          body: String(step?.body || '')
            .trim()
            .slice(0, 1500),
        }))
        .filter((s) => s.title && s.body)
        .slice(0, 8)
    : [];
  const local = buildLocalResearchBriefRun(brief, locale);
  return {
    packId: 'research-brief',
    goal: 'data-analysis',
    bridge: 'runner',
    question: question.slice(0, 1200),
    sources: String(parsed.sources || local.sources)
      .trim()
      .slice(0, 1200),
    analysisPlan: String(parsed.analysisPlan || local.analysisPlan)
      .trim()
      .slice(0, 1500),
    findingsTemplate: String(parsed.findingsTemplate || local.findingsTemplate)
      .trim()
      .slice(0, 1200),
    steps: steps.length >= 3 ? steps : local.steps,
    source: llmSource || 'provider',
  };
}

// --- unified entry ---

/**
 * @param {string} packId
 * @param {string} brief
 * @param {string} [locale]
 */
export async function runPack(packId, brief, locale = 'tr') {
  const id = String(packId || '').trim();
  if (!isRunnablePack(id)) {
    throw new Error('not_runnable');
  }
  if (id === 'content-studio') return runContentStudioPack(brief, locale);
  if (id === 'sales-outreach') return runSalesOutreachPack(brief, locale);
  if (id === 'meeting-to-action') return runMeetingToActionPack(brief, locale);
  if (id === 'social-launch') return runSocialLaunchPack(brief, locale);
  if (id === 'pitch-deck') return runPitchDeckPack(brief, locale);
  if (id === 'seo-brief') return runSeoBriefPack(brief, locale);
  if (id === 'support-kit') return runSupportKitPack(brief, locale);
  if (id === 'code-scaffold') return runCodeScaffoldPack(brief, locale);
  if (id === 'legal-review') return runLegalReviewPack(brief, locale);
  if (id === 'research-brief') return runResearchBriefPack(brief, locale);
  throw new Error('not_runnable');
}

/**
 * Normalize multi-step sections for UI.
 * @param {object} run
 * @returns {{ id: string, title: string, body: string }[]}
 */
export function extractRunSteps(run) {
  if (!run) return [];
  if (Array.isArray(run.steps) && run.steps.length) {
    return run.steps
      .map((step, index) => ({
        id: String(step?.id || `step-${index + 1}`),
        title: String(step?.title || '').trim(),
        body: String(step?.body || '').trim(),
      }))
      .filter((s) => s.title && s.body);
  }
  return [];
}

/**
 * @param {object} run
 * @param {string} [locale]
 */
export function formatPackArtifact(run, locale = 'tr') {
  if (!run) return '';
  if (run.packId === 'content-studio') return formatContentStudioArtifact(run, locale);
  if (run.packId === 'sales-outreach') return formatSalesOutreachArtifact(run, locale);
  if (run.packId === 'meeting-to-action') return formatMeetingToActionArtifact(run, locale);
  if (run.packId === 'social-launch') return formatSocialLaunchArtifact(run, locale);
  if (run.packId === 'pitch-deck') return formatPitchDeckArtifact(run, locale);
  if (run.packId === 'seo-brief') return formatSeoBriefArtifact(run, locale);
  if (run.packId === 'support-kit') return formatSupportKitArtifact(run, locale);
  if (run.packId === 'code-scaffold') return formatCodeScaffoldArtifact(run);
  if (run.packId === 'legal-review') return formatLegalReviewArtifact(run);
  if (run.packId === 'research-brief') return formatResearchBriefArtifact(run);
  return String(run.draft || run.summary || '').trim();
}

/**
 * UI-facing public summary of run payload (no huge internal dumps).
 */
export function summarizeRunForClient(run) {
  if (!run) return null;
  const steps = extractRunSteps(run);
  if (run.packId === 'content-studio') {
    return {
      packId: run.packId,
      source: run.source,
      draft: run.draft,
      imagePrompt: run.imagePrompt,
      seo: run.seo,
      steps,
    };
  }
  if (run.packId === 'sales-outreach') {
    return {
      packId: run.packId,
      source: run.source,
      subjects: run.subjects,
      sequence: run.sequence,
      crmStages: run.crmStages,
      followUpRules: run.followUpRules,
      steps,
    };
  }
  if (run.packId === 'meeting-to-action') {
    return {
      packId: run.packId,
      source: run.source,
      summary: run.summary,
      actions: run.actions,
      automationMap: run.automationMap,
      steps,
    };
  }
  if (run.packId === 'social-launch') {
    return {
      packId: run.packId,
      source: run.source,
      calendar: run.calendar,
      posts: run.posts,
      imagePrompts: run.imagePrompts,
      schedulePlan: run.schedulePlan,
      steps,
    };
  }
  if (run.packId === 'pitch-deck') {
    return {
      packId: run.packId,
      source: run.source,
      narrative: run.narrative,
      slides: run.slides,
      visualPrompts: run.visualPrompts,
      speakerNotes: run.speakerNotes,
      steps,
    };
  }
  if (run.packId === 'seo-brief') {
    return {
      packId: run.packId,
      source: run.source,
      keywords: run.keywords,
      outline: run.outline,
      meta: run.meta,
      contentBrief: run.contentBrief,
      steps,
    };
  }
  if (run.packId === 'support-kit') {
    return {
      packId: run.packId,
      source: run.source,
      macros: run.macros,
      toneGuide: run.toneGuide,
      escalation: run.escalation,
      faq: run.faq,
      steps,
    };
  }
  if (run.packId === 'code-scaffold') {
    return {
      packId: run.packId,
      source: run.source,
      requirements: run.requirements,
      fileTree: run.fileTree,
      scaffold: run.scaffold,
      testPlan: run.testPlan,
      steps,
    };
  }
  if (run.packId === 'legal-review') {
    return {
      packId: run.packId,
      source: run.source,
      scope: run.scope,
      risks: run.risks,
      questions: run.questions,
      redlines: run.redlines,
      disclaimer: run.disclaimer,
      steps,
    };
  }
  if (run.packId === 'research-brief') {
    return {
      packId: run.packId,
      source: run.source,
      question: run.question,
      sources: run.sources,
      analysisPlan: run.analysisPlan,
      findingsTemplate: run.findingsTemplate,
      steps,
    };
  }
  return { packId: run.packId, source: run.source, steps };
}
