-- Genişletilmiş kategori seti (161 kanonik kategori)
-- Mevcut slug'lara dokunmaz; yalnızca eksikleri ekler.
INSERT INTO public.categories (name, slug)
SELECT v.name, v.slug
FROM (
  VALUES
    ('Görsel & Video', 'gorsel-video'),
    ('Görsel Üretim', 'gorsel-uretim'),
    ('Video Üretim', 'video-uretim'),
    ('Fotoğraf Düzenleme', 'fotograf-duzenleme'),
    ('Görsel İyileştirme', 'gorsel-iyilestirme'),
    ('Arka Plan Kaldırma', 'arka-plan-kaldirma'),
    ('Logo & Marka', 'logo-marka'),
    ('UI/UX Tasarım', 'ui-ux-tasarim'),
    ('Tasarım', 'tasarim'),
    ('3D Modelleme', '3d-modelleme'),
    ('3D Animasyon', '3d-animasyon'),
    ('Avatar & Dijital İnsan', 'avatar-dijital-insan'),
    ('Motion Graphics', 'motion-graphics'),
    ('Storyboard', 'storyboard'),
    ('Thumbnail & Kapak', 'thumbnail-kapak'),
    ('Ses & Müzik', 'ses-muzik'),
    ('Ses Klonlama', 'ses-klonlama'),
    ('Podcast & Yayın', 'podcast-yayin'),
    ('Müzik Üretim', 'muzik-uretim'),
    ('Ses Efektleri', 'ses-efektleri'),
    ('Ses Temizleme', 'ses-temizleme'),
    ('Şarkı Sözü', 'sarki-sozu'),
    ('Radyo & Yayın', 'radyo-yayin'),
    ('Enstrüman AI', 'enstruman-ai'),
    ('DJ & Mix', 'dj-mix'),
    ('Metin Yazarlığı', 'metin-yazarligi'),
    ('Çeviri & Dil', 'ceviri-dil'),
    ('Kopya Yazarlığı', 'kopya-yazarligi'),
    ('Senaryo Yazımı', 'senaryo-yazimi'),
    ('Hikâye & Roman', 'hikaye-roman'),
    ('Özetleme', 'ozetleme'),
    ('Dilbilgisi & Düzenleme', 'dilbilgisi-duzenleme'),
    ('Transkripsiyon', 'transkripsiyon'),
    ('Altyazı', 'altyazi'),
    ('Sunum & Doküman', 'sunum-dokuman'),
    ('CV & Kariyer', 'cv-kariyer'),
    ('E-posta Yazımı', 'e-posta-yazimi'),
    ('Haber & Gazetecilik', 'haber-gazetecilik'),
    ('Akademik Yazım', 'akademik-yazim'),
    ('Prompt Mühendisliği', 'prompt-muhendisligi'),
    ('Kod & Yazılım', 'kod-yazilim'),
    ('Geliştirici Araçları', 'gelistirici-araclari'),
    ('No-Code / Low-Code', 'no-code-low-code'),
    ('MLOps & Model', 'mlops-model'),
    ('Veritabanı & Bilgi', 'veritabani-bilgi'),
    ('API & Entegrasyon', 'api-entegrasyon'),
    ('Test & QA', 'test-qa'),
    ('DevOps & Bulut', 'devops-bulut'),
    ('Güvenlik Kod', 'guvenlik-kod'),
    ('Mobil Geliştirme', 'mobil-gelistirme'),
    ('Web Geliştirme', 'web-gelistirme'),
    ('Veri Bilimi', 'veri-bilimi'),
    ('SQL & Veri', 'sql-veri'),
    ('Kod İnceleme', 'kod-inceleme'),
    ('Dokümantasyon Kod', 'dokumantasyon-kod'),
    ('Terminal & CLI', 'terminal-cli'),
    ('Donanım & IoT', 'donanim-iot'),
    ('Yarı İletken & Chip', 'yari-iletken-chip'),
    ('Üretkenlik', 'uretkenlik'),
    ('Kişisel Asistan', 'kisisel-asistan'),
    ('Otomasyon & Ajan', 'otomasyon-ajan'),
    ('Toplantı & Not', 'toplanti-not'),
    ('Bilgi Yönetimi', 'bilgi-yonetimi'),
    ('Görev Yönetimi', 'gorev-yonetimi'),
    ('Takvim & Zaman', 'takvim-zaman'),
    ('Not Alma', 'not-alma'),
    ('Form & Anket', 'form-anket'),
    ('İşbirliği', 'isbirligi'),
    ('CRM & Pipeline', 'crm-pipeline'),
    ('Pazarlama', 'pazarlama'),
    ('Sosyal Medya', 'sosyal-medya'),
    ('SEO', 'seo'),
    ('Reklam & Performance', 'reklam-performance'),
    ('Influencer', 'influencer'),
    ('E-posta Pazarlama', 'e-posta-pazarlama'),
    ('Satış & CRM', 'satis-crm'),
    ('E-Ticaret', 'e-ticaret'),
    ('Ürün Fotoğrafı', 'urun-fotograf'),
    ('Fiyatlandırma', 'fiyatlandirma'),
    ('Müşteri Destek', 'musteri-destek'),
    ('Canlı Sohbet', 'canli-sohbet'),
    ('İtibar Yönetimi', 'itibar-yonetimi'),
    ('Pazar Araştırması', 'pazar-arastirmasi'),
    ('İş Dünyası', 'is-dunyasi'),
    ('Finans & Yatırım', 'finans-yatirim'),
    ('Muhasebe', 'muhasebe'),
    ('Bütçe & Harcama', 'butce-harcama'),
    ('İnsan Kaynakları', 'insan-kaynaklari'),
    ('Hukuk & Uyumluluk', 'hukuk-uyumluluk'),
    ('Sözleşme İnceleme', 'sozlesme-inceleme'),
    ('Güvenlik & Siber', 'guvenlik-siber'),
    ('Kimlik & Fraud', 'kimlik-fraud'),
    ('İçerik Moderasyon', 'icerik-moderasyon'),
    ('Ürün Yönetimi', 'urun-yonetimi'),
    ('Girişimcilik', 'girisimcilik'),
    ('Danışmanlık', 'danismanlik'),
    ('Operasyon', 'operasyon'),
    ('Tedarik Zinciri', 'tedarik-zinciri'),
    ('Depo & Envanter', 'depo-envanter'),
    ('Chatbotlar', 'chatbotlar'),
    ('Kurumsal Chatbot', 'kurumsal-chatbot'),
    ('Sesli Asistan', 'sesli-asistan'),
    ('Arama Motoru', 'arama-motoru'),
    ('Araştırma & Akademik', 'arastirma-akademik'),
    ('Web Araştırma', 'web-arastirma'),
    ('Belge Soru-Cevap', 'belge-soru-cevap'),
    ('Bilgi Bankası', 'bilgi-bankasi'),
    ('Eğitim', 'egitim'),
    ('Dil Öğrenme', 'dil-ogrenme'),
    ('Sınav Hazırlık', 'sinav-hazirlik'),
    ('Çocuk & Ebeveyn', 'cocuk-ebeveyn'),
    ('Sağlık & Yaşam', 'saglik-yasam'),
    ('Sağlıklı Yaşam', 'saglikli-yasam'),
    ('Fitness', 'fitness'),
    ('Beslenme', 'beslenme'),
    ('Mental Sağlık', 'mental-saglik'),
    ('Erişilebilirlik', 'erisilebilirlik'),
    ('Hayırseverlik', 'hayirseverlik'),
    ('Emlak & İnşaat', 'emlak-insaat'),
    ('İç Mimarlık', 'ic-mimarlik'),
    ('Harita & Konum', 'harita-konum'),
    ('Seyahat', 'seyahat'),
    ('Otel & Konaklama', 'otel-konaklama'),
    ('Otomotiv', 'otomotiv'),
    ('Lojistik', 'lojistik'),
    ('Tarım', 'tarim'),
    ('İklim & Enerji', 'iklim-enerji'),
    ('Çevre', 'cevre'),
    ('Moda', 'moda'),
    ('Güzellik', 'guzellik'),
    ('Yemek & Mutfak', 'yemek-mutfak'),
    ('Şarap & İçecek', 'sarap-icecek'),
    ('Evcil Hayvan', 'evcil-hayvan'),
    ('Spor', 'spor'),
    ('Hukuk Bürosu', 'hukuk-burosu'),
    ('Sigorta', 'sigorta'),
    ('Bankacılık', 'bankacilik'),
    ('Kripto & Web3', 'kripto-web3'),
    ('Bilim & Lab', 'bilim-lab'),
    ('Kimya & Malzeme', 'kimya-malzeme'),
    ('Uzay', 'uzay'),
    ('Savunma', 'savunma'),
    ('Oyun & Eğlence', 'oyun-eglence'),
    ('Oyun Hikâyesi', 'oyun-hikayesi'),
    ('Oyun Asset', 'oyun-asset'),
    ('Film & Dizi', 'film-dizi'),
    ('Yayıncılık', 'yayincilik'),
    ('Streaming', 'streaming'),
    ('QR & Barkod', 'qr-barkod'),
    ('Paylaşım & Viral', 'paylasim-viral'),
    ('Topluluk Yönetimi', 'topluluk-yonetimi'),
    ('İçerik Takvimi', 'icerik-takvimi'),
    ('A/B Test', 'ab-test'),
    ('Analitik Dashboard', 'analitik-dashboard'),
    ('İş Zekâsı', 'is-zekasi'),
    ('Tahminleme', 'tahminleme'),
    ('Kişiselleştirme', 'kisisellestirme'),
    ('Arama Deneyimi', 'arama-deneyimi'),
    ('Müşteri Yolculuğu', 'musteri-yolculugu'),
    ('İnovasyon', 'inovasyon'),
    ('Diğer', 'diger')
) AS v(name, slug)
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories c WHERE c.slug = v.slug
);
